#!/usr/bin/env python3
"""Generate tools/rpy_lib/rpy_ast.py from tools/rpy_lib/rast.py.

rast.py is the single source of truth: a pymetaterp-derived PEG parser for a
Python subset, written to run as minipy bytecode.  rpy_ast.py is the *same*
parser adjusted so py2c can compile it straight to native C.  The adjustments
are small, mechanical, and each works around a specific, documented py2c gap
(see MINIPY.md, "Porting rast.py to native code").

This script applies exactly those transforms.  Every transform asserts that its
input pattern is present, so if rast.py changes in a way that invalidates one,
generation fails loudly instead of silently producing a broken parser.

    python3 tools/rpy_lib/build_rpy_ast.py            # regenerate rpy_ast.py
    python3 tools/rpy_lib/build_rpy_ast.py --check     # verify it's up to date
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RAST = os.path.join(HERE, "rast.py")
RPY_AST = os.path.join(HERE, "rpy_ast.py")


def _sub(s, old, new, what):
    """Replace exactly one occurrence of `old`, asserting it is present."""
    n = s.count(old)
    if n != 1:
        raise SystemExit(
            "build_rpy_ast: transform %r expected 1 match in rast.py, found %d.\n"
            "rast.py has drifted; update build_rpy_ast.py to match." % (what, n))
    return s.replace(old, new)


HEADER = ('"""py2c-compilable port of rast.py -- GENERATED by build_rpy_ast.py, '
          'do not edit.\n\n'
          'Regenerate with:  python3 tools/rpy_lib/build_rpy_ast.py\n'
          'Source of truth:  tools/rpy_lib/rast.py\n'
          'The transforms and the py2c gaps they work around are documented in '
          'MINIPY.md.\n"""\n')

MAIN = '''

# ---------------------------------------------------------------------------
# Self-test entry point.  Compiled to a native `main` by py2c; also runnable
# under CPython (`python3 rpy_ast.py`).  Parses a spread of Python snippets and
# prints a canonical pre-order dump of each tree -- byte-identical to CPython.
# ---------------------------------------------------------------------------

def _dump(node, depth):
    if not is_node(node):
        print(". " * depth + "leaf " + str(node))
        return
    print(". " * depth + node.name)
    for ch in node.children:
        _dump(ch, depth + 1)

def main() -> "int":
    srcs = ["x = 1 + 2 * 3\\n", "y = (1 + 2) * 3\\n",
            "def f(a, b):\\n    return a + b\\n",
            "if x > 0:\\n    y = 1\\nelse:\\n    y = 2\\n",
            "while n:\\n    n = n - 1\\n",
            "for i in items:\\n    total = total + i\\n",
            "vals = [1, 2, 3]\\n", "d = {1: 2, 3: 4}\\n",
            "r = f(a, b) + g(c)\\n", "ok = a == b and c != d\\n"]
    for src in srcs:
        print("### " + src)
        _dump(parse_python(src), 0)
    return 0

if __name__ == "__main__":
    main()
'''


def generate():
    s = open(RAST).read()

    # (#3 in MINIPY.md) float("inf") does not yield infinity -> lazy large int.
    s = _sub(s, 'inf = float("inf")',
             'inf = None   # built in _ensure_tables (py2c defers non-const module globals)',
             "inf-float")

    # (#1) type(x)==T does not compile -> isinstance(x, T).
    s = _sub(s, 'if type(root) != list:', 'if not isinstance(root, list):',
             "type-root-list")
    s = _sub(s, 'if all(type(x) == str for x in flat):',
             'if all(isinstance(x, str) for x in flat):', "type-all-str")

    # (#1-adjacent) dict/set comprehension for rules -> explicit loop.
    s = _sub(s,
             "        self.rules = {rule.children[0].children[0]: rule\n"
             "                      for rule in grammar_tree.children}",
             "        self.rules = {}\n"
             "        for rule in grammar_tree.children:\n"
             "            self.rules[rule.children[0].children[0]] = rule",
             "rules-comprehension")

    # (#4) dict([2-char strings]) leaves values null -> explicit dict literal.
    s = _sub(s,
             '                chars = dict(["\'\'", \'""\', "t\\t", "n\\n", "r\\r", "b\\b", "f\\f", "\\\\\\\\"])',
             '                chars = {"\'": "\'", \'"\': \'"\', "t": "\\t", "n": "\\n", "r": "\\r",\n'
             '                         "b": "\\b", "f": "\\f", "\\\\": "\\\\"}',
             "escaped-char-dict")

    # (#2) non-constant obj module globals aren't initialized -> lazy _ensure_tables.
    s = _sub(s,
             'binary_ops = ((">=", "<=", "<>", "<", ">", "==", "!=",\n'
             '               "in", "not in", "is not", "is"),\n'
             '              ("|",), ("^",), ("&",), ("<<", ">>"), ("+", "-"),\n'
             '              ("*", "/", "%", "//"), ("**",))\n'
             'priority = {op:i for i, ops in enumerate(binary_ops) for op in ops}\n'
             'expr_ops = binary_ops[1:]',
             '# Non-constant module globals are left None here: py2c does not run a module\n'
             '# initializer for a standalone main() program, but a static obj defaults to\n'
             '# None, so the lazy builder below (same idea as _PYI) populates them on first\n'
             '# use.  _ensure_tables() runs before any parsing, so reformat_binary / any_token\n'
             '# see filled-in tables.\n'
             'binary_ops = None\n'
             'priority = None\n'
             '\n'
             'def _ensure_tables():\n'
             '    global binary_ops, priority, inf\n'
             '    if binary_ops is not None:\n'
             '        return\n'
             '    inf = 1000000000\n'
             '    binary_ops = ((">=", "<=", "<>", "<", ">", "==", "!=",\n'
             '                   "in", "not in", "is not", "is"),\n'
             '                  ("|",), ("^",), ("&",), ("<<", ">>"), ("+", "-"),\n'
             '                  ("*", "/", "%", "//"), ("**",))\n'
             '    pri = {}\n'
             '    idx = 0\n'
             '    for ops in binary_ops:\n'
             '        for op in ops:\n'
             '            pri[op] = idx\n'
             '        idx = idx + 1\n'
             '    priority = pri',
             "binary_ops-block")

    # (#7) param inferred as int -> annotate obj.
    s = _sub(s, 'def _rb_parse(lhs, tokens, index):',
             'def _rb_parse(lhs: "obj", tokens, index):', "rb_parse-annot")
    s = _sub(s, 'def reformat_binary(start, tokens):',
             'def reformat_binary(start: "obj", tokens):', "reformat_binary-annot")
    s = _sub(s, '    lhs, index = start, 0',
             '    lhs = start\n    index = 0', "lhs-index-split")

    # expr_ops global removed -> inline slice.
    s = _sub(s, '    ops = binary_ops if binary else expr_ops',
             '    ops = binary_ops if binary else binary_ops[1:]', "expr_ops-inline")

    # (#2) big literals -> functions (so they build on call, not at import).
    s = _sub(s, '\ngrammar = r"""', '\ndef _grammar():\n    return r"""', "grammar-fn")
    s = _sub(s, '\npython_grammar = r"""',
             '\ndef _python_grammar():\n    return r"""', "python_grammar-fn")
    s = _sub(s, '\nextra = r"""', '\ndef _extra():\n    return r"""', "extra-fn")
    s = _sub(s, "\ntree = ['And',", "\ndef _meta_tree():\n    return ['And',", "tree-fn")

    # _python_interp: call _ensure_tables and use the functions.
    s = _sub(s,
             "        i1 = Interpreter(simple_wrap_tree(tree))\n"
             "        mt1 = i1.match(i1.rules['grammar'].children[-1], grammar + extra)",
             "        _ensure_tables()\n"
             "        ex = _extra()\n"
             "        i1 = Interpreter(simple_wrap_tree(_meta_tree()))\n"
             "        mt1 = i1.match(i1.rules['grammar'].children[-1], _grammar() + ex)",
             "python_interp-stage1")
    s = _sub(s,
             "        mt2 = i2.match(i2.rules['grammar'].children[-1], python_grammar + extra)",
             "        mt2 = i2.match(i2.rules['grammar'].children[-1], _python_grammar() + ex)",
             "python_interp-stage2")

    # (#6) virtual dispatch needs a TypeInfo -> isinstance narrowing.
    s = _sub(s,
             "    return pyi.match(pyi.rules['file_input'].children[-1], source)",
             "    if isinstance(pyi, Interpreter):\n"
             "        return pyi.match(pyi.rules['file_input'].children[-1], source)\n"
             "    return None",
             "parse_python-narrow")

    # (#5) self-test main with an int return annotation.
    s = s.rstrip() + "\n" + MAIN

    # Replace rast.py's module docstring with a generated-file banner.
    assert s.startswith('"""'), "rast.py should start with a docstring"
    end = s.index('"""', 3) + 3
    s = HEADER + s[end:].lstrip("\n")
    return s


def main(argv):
    generated = generate()
    if "--check" in argv:
        current = open(RPY_AST).read() if os.path.exists(RPY_AST) else None
        if current == generated:
            print("rpy_ast.py is up to date with rast.py")
            return 0
        print("rpy_ast.py is STALE -- run: python3 tools/rpy_lib/build_rpy_ast.py")
        return 1
    open(RPY_AST, "w").write(generated)
    print("wrote %s (%d lines) from rast.py" % (RPY_AST, generated.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
