#!/usr/bin/env python3
"""Generate benchmarks/minipy/minipy2c.py -- the "true" minipy benchmark.

minipy has no imports, so the runnable benchmark is the concatenation of
rast.py (the Python parser) + minipy2c.py (the mini Python->C transpiler) + a
driver that parses and transpiles a real multi-function Python program many
times and checksums the emitted C. The result is a single self-contained file
the standard 3-way harness (cpython / ref VM / native) and the benchmark runner
can execute directly.

Re-run this whenever rast.py or minipy2c.py change:

    python3 tools/rpy_lib/build_minipy2c_bench.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
RAST = os.path.join(HERE, "rast.py")
M2C = os.path.join(HERE, "minipy2c.py")
OUT = os.path.join(ROOT, "benchmarks", "minipy", "minipy2c.py")

# A real, multi-function Python program: recursion, while loops, if/else,
# arithmetic, comparisons and calls -- enough to exercise the whole pipeline.
SAMPLE = (
    "def add(a, b):\n    return a + b\n"
    "def fib(n):\n    if n < 2:\n        return n\n"
    "    else:\n        return fib(n - 1) + fib(n - 2)\n"
    "def sumto(n):\n    total = 0\n    i = 0\n"
    "    while i < n:\n        total = total + i\n        i = i + 1\n    return total\n"
    "def classify(x):\n    if x < 0:\n        r = 0\n    else:\n        r = 1\n    return r\n"
)

# N=15 keeps the no-GC bump arena comfortably under 1 GiB (it tops out near 35)
# while still running ~1s natively and exercising parse+transpile 15 times.
DRIVER = '''

# ---- benchmark driver (generated by build_minipy2c_bench.py) ----------------
SAMPLE = %r

N = 15
total = 0
k = 0
while k < N:
    t = Transpiler()
    code = t.transpile(SAMPLE)
    total = total + len(code)
    k = k + 1
print(total)
'''

HEADER = (
    "# GENERATED by tools/rpy_lib/build_minipy2c_bench.py -- do not edit by hand.\n"
    "# = rast.py (parser) + minipy2c.py (Python->C transpiler) + benchmark driver.\n"
    "# The real-world minipy benchmark: parse + transpile Python, end to end.\n\n"
)


def main():
    combined = HEADER + open(RAST).read() + open(M2C).read() + DRIVER % SAMPLE
    with open(OUT, "w") as f:
        f.write(combined)
    print("wrote %s (%d bytes)" % (OUT, len(combined)))


if __name__ == "__main__":
    main()
