"""rpyqt -- a restricted, PyQt-compatible widget API built on rwayland.

This is *not* bound to Qt. It is a small emulation layer: enough of the PyQt5
surface (QApplication, QWidget, QLabel, QPushButton, QVBoxLayout, a `clicked`
signal) that PyQt-shaped code transpiles and runs as a native Wayland client,
software-rendered into the rwayland framebuffer. Users who do not want the Qt
shape can drop down to `rwayland` directly.

    from rpyqt import QApplication, QWidget, QVBoxLayout, QLabel, QPushButton

    def main() -> int:
        app = QApplication()
        win = QWidget()
        win.setWindowTitle("counter")
        layout = QVBoxLayout()
        label = QLabel("COUNT 0")
        button = QPushButton("INCREMENT")
        button.clicked.connect(on_click)     # a no-arg handler
        layout.addWidget(label)
        layout.addWidget(button)
        win.setLayout(layout)
        return app.exec_(win)

Rendering: each widget draws itself into the XRGB8888 framebuffer with a built
-in 5x7 bitmap font (uppercase letters, digits, space, and a few symbols). The
rpyqt binds the generated Wayland runtime directly (rwl_run + the rw_* hooks),
so the Wayland glue is machine-generated by py2c -- no C is hand-written.

Scope: vertical layout only; one signal (`clicked`); a no-arg handler. The aim
is to show the adaptation path PyQt -> rpyqt -> Wayland, not API completeness.
"""
import rpy_ctypes as ctypes

# rpyqt is self-contained over the generated Wayland runtime: it binds rwl_run()
# (resolved from rwayland_rt.o at link time) and defines the five rw_* hooks the
# runtime calls. It deliberately does NOT subclass rwayland.Window, so every
# class here is locally rooted and shares one consistent vtable layout -- mixing
# a cross-module-rooted class with local hierarchies in a single module yields
# inconsistent vtables under py2c.
_wl = ctypes.CDLL("libwayland-client.so.0")
_wl.rwl_run.restype = ctypes.c_int
_wl.rwl_run.argtypes = []

ACTION_QUIT = 0
ACTION_MOVE = 1
ACTION_REDRAW = 2
ACTION_NONE = 3


def fill_rect(fb: "u32*", fb_w: int, fb_h: int,
              x: int, y: int, w: int, h: int, color: int) -> None:
    yy = y
    y1 = y + h
    while yy < y1:
        if yy >= 0 and yy < fb_h:
            xx = x
            x1 = x + w
            while xx < x1:
                if xx >= 0 and xx < fb_w:
                    fb[yy * fb_w + xx] = color
                xx = xx + 1
        yy = yy + 1

# ---- geometry / palette --------------------------------------------------
WIN_W = 480
WIN_H = 320
PAD = 16
ROW_H = 44
GAP = 12

COL_BG = 0xFFF0F0F0
COL_LABEL_BG = 0xFFF0F0F0
COL_BTN = 0xFF0088FF
COL_BTN_DOWN = 0xFF005FBF
COL_TEXT = 0xFF202020
COL_BTN_TEXT = 0xFFFFFFFF


# ---- 5x7 bitmap font -----------------------------------------------------
# Each glyph is 7 rows; each row's low 5 bits are pixels (MSB = leftmost).
# Covers A-Z, 0-9, space, ':' and '.'; unknown chars render blank.
def glyph_row(ch: int, row: int) -> int:
    # Letters
    if ch == 65:   # A
        r = [0x0E, 0x11, 0x11, 0x1F, 0x11, 0x11, 0x11]
    elif ch == 66:  # B
        r = [0x1E, 0x11, 0x1E, 0x11, 0x11, 0x11, 0x1E]
    elif ch == 67:  # C
        r = [0x0E, 0x11, 0x10, 0x10, 0x10, 0x11, 0x0E]
    elif ch == 68:  # D
        r = [0x1E, 0x11, 0x11, 0x11, 0x11, 0x11, 0x1E]
    elif ch == 69:  # E
        r = [0x1F, 0x10, 0x1E, 0x10, 0x10, 0x10, 0x1F]
    elif ch == 70:  # F
        r = [0x1F, 0x10, 0x1E, 0x10, 0x10, 0x10, 0x10]
    elif ch == 71:  # G
        r = [0x0E, 0x11, 0x10, 0x17, 0x11, 0x11, 0x0F]
    elif ch == 72:  # H
        r = [0x11, 0x11, 0x1F, 0x11, 0x11, 0x11, 0x11]
    elif ch == 73:  # I
        r = [0x0E, 0x04, 0x04, 0x04, 0x04, 0x04, 0x0E]
    elif ch == 74:  # J
        r = [0x07, 0x02, 0x02, 0x02, 0x12, 0x12, 0x0C]
    elif ch == 75:  # K
        r = [0x11, 0x12, 0x14, 0x18, 0x14, 0x12, 0x11]
    elif ch == 76:  # L
        r = [0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x1F]
    elif ch == 77:  # M
        r = [0x11, 0x1B, 0x15, 0x15, 0x11, 0x11, 0x11]
    elif ch == 78:  # N
        r = [0x11, 0x19, 0x15, 0x13, 0x11, 0x11, 0x11]
    elif ch == 79:  # O
        r = [0x0E, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0E]
    elif ch == 80:  # P
        r = [0x1E, 0x11, 0x11, 0x1E, 0x10, 0x10, 0x10]
    elif ch == 81:  # Q
        r = [0x0E, 0x11, 0x11, 0x11, 0x15, 0x12, 0x0D]
    elif ch == 82:  # R
        r = [0x1E, 0x11, 0x11, 0x1E, 0x14, 0x12, 0x11]
    elif ch == 83:  # S
        r = [0x0F, 0x10, 0x10, 0x0E, 0x01, 0x01, 0x1E]
    elif ch == 84:  # T
        r = [0x1F, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04]
    elif ch == 85:  # U
        r = [0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0E]
    elif ch == 86:  # V
        r = [0x11, 0x11, 0x11, 0x11, 0x11, 0x0A, 0x04]
    elif ch == 87:  # W
        r = [0x11, 0x11, 0x11, 0x15, 0x15, 0x1B, 0x11]
    elif ch == 88:  # X
        r = [0x11, 0x0A, 0x04, 0x04, 0x04, 0x0A, 0x11]
    elif ch == 89:  # Y
        r = [0x11, 0x0A, 0x04, 0x04, 0x04, 0x04, 0x04]
    elif ch == 90:  # Z
        r = [0x1F, 0x01, 0x02, 0x04, 0x08, 0x10, 0x1F]
    elif ch == 48:  # 0
        r = [0x0E, 0x11, 0x13, 0x15, 0x19, 0x11, 0x0E]
    elif ch == 49:  # 1
        r = [0x04, 0x0C, 0x04, 0x04, 0x04, 0x04, 0x0E]
    elif ch == 50:  # 2
        r = [0x0E, 0x11, 0x01, 0x02, 0x04, 0x08, 0x1F]
    elif ch == 51:  # 3
        r = [0x1F, 0x02, 0x04, 0x02, 0x01, 0x11, 0x0E]
    elif ch == 52:  # 4
        r = [0x02, 0x06, 0x0A, 0x12, 0x1F, 0x02, 0x02]
    elif ch == 53:  # 5
        r = [0x1F, 0x10, 0x1E, 0x01, 0x01, 0x11, 0x0E]
    elif ch == 54:  # 6
        r = [0x06, 0x08, 0x10, 0x1E, 0x11, 0x11, 0x0E]
    elif ch == 55:  # 7
        r = [0x1F, 0x01, 0x02, 0x04, 0x08, 0x08, 0x08]
    elif ch == 56:  # 8
        r = [0x0E, 0x11, 0x11, 0x0E, 0x11, 0x11, 0x0E]
    elif ch == 57:  # 9
        r = [0x0E, 0x11, 0x11, 0x0F, 0x01, 0x02, 0x0C]
    elif ch == 58:  # :
        r = [0x00, 0x04, 0x00, 0x00, 0x00, 0x04, 0x00]
    elif ch == 46:  # .
        r = [0x00, 0x00, 0x00, 0x00, 0x00, 0x0C, 0x0C]
    else:           # space / unknown
        r = [0, 0, 0, 0, 0, 0, 0]
    return r[row]


def draw_char(fb: "u32*", fbw: int, fbh: int, x: int, y: int,
              ch: int, scale: int, color: int) -> None:
    row = 0
    while row < 7:
        bits = glyph_row(ch, row)
        col = 0
        while col < 5:
            on = (bits >> (4 - col)) & 1
            if on:
                fill_rect(fb, fbw, fbh,
                                   x + col * scale, y + row * scale,
                                   scale, scale, color)
            col = col + 1
        row = row + 1


def draw_text(fb: "u32*", fbw: int, fbh: int, x: int, y: int,
              text: "char*", scale: int, color: int) -> None:
    n = len(text)
    i = 0
    cx = x
    while i < n:
        draw_char(fb, fbw, fbh, cx, y, ord(text[i]), scale, color)
        cx = cx + 6 * scale
        i = i + 1


# ---- signal --------------------------------------------------------------
class Signal:
    """A one-slot signal: connect(fn) stores a no-arg handler, emit() calls it."""

    def __init__(self):
        self.handler = None

    def connect(self, fn: "obj") -> None:
        self.handler = fn

    def emit(self) -> None:
        f = self.handler
        if f is not None:
            f()


# ---- widget hierarchy (all local -> one consistent vtable) ---------------
class Widget:
    """Base child widget. Geometry is assigned by the layout."""

    def __init__(self):
        self.x = 0
        self.y = 0
        self.w = 0
        self.h = 0
        self.text = ""

    def setText(self, text: "char*") -> None:
        self.text = text

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        return

    def on_press(self) -> int:
        return ACTION_NONE


class QLabel(Widget):
    def __init__(self, text: "char*"):
        super().__init__()
        self.text = text

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_LABEL_BG)
        draw_text(fb, fbw, fbh, self.x + 8, self.y + 14, self.text, 3, COL_TEXT)


class QPushButton(Widget):
    def __init__(self, text: "char*"):
        super().__init__()
        self.text = text
        self.clicked = Signal()

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_BTN)
        draw_text(fb, fbw, fbh, self.x + 12, self.y + 14, self.text, 3,
                  COL_BTN_TEXT)

    def on_press(self) -> int:
        self.clicked.emit()
        return ACTION_REDRAW


class _QtObject:
    """Empty local base. Giving QVBoxLayout/QWidget a base makes them
    object-model (vtable-backed) so an instance can be boxed into an `obj` and
    dispatched virtually. Safe here because rpyqt has no cross-module-rooted
    class: every hierarchy is local, so they all share one consistent vtable."""
    pass


class QVBoxLayout(_QtObject):
    """A vertical stack of widgets."""

    def __init__(self):
        super().__init__()
        self.items: "list[Widget]" = []

    def addWidget(self, w: "obj") -> None:
        self.items.append(w)

    def layout(self, x: int, y: int, width: int) -> None:
        cy = y
        i = 0
        n = len(self.items)
        while i < n:
            w = self.items[i]
            w.x = x
            w.y = cy
            w.w = width
            w.h = ROW_H
            cy = cy + ROW_H + GAP
            i = i + 1

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        i = 0
        n = len(self.items)
        while i < n:
            self.items[i].paint(fb, fbw, fbh)
            i = i + 1

    def press(self, px: int, py: int) -> int:
        i = 0
        n = len(self.items)
        while i < n:
            w = self.items[i]
            if px >= w.x and px < w.x + w.w and py >= w.y and py < w.y + w.h:
                return w.on_press()
            i = i + 1
        return ACTION_NONE


# ---- top-level window ----------------------------------------------------
class QWidget(_QtObject):
    """A top-level window hosting a layout. Painted/pointer-routed by the
    module-level rw_* trampolines, which the generated runtime calls."""

    def __init__(self):
        super().__init__()
        self.box = None
        self.title = "rpyqt"
        self.width = WIN_W
        self.height = WIN_H

    def setWindowTitle(self, title: "char*") -> None:
        self.title = title

    def setLayout(self, box: "obj") -> None:
        self.box = box
        b = self._box()
        b.layout(PAD, PAD, WIN_W - 2 * PAD)

    def _box(self) -> "QVBoxLayout*":
        return self.box

    def on_paint(self, fb: "u32*") -> None:
        fill_rect(fb, WIN_W, WIN_H, 0, 0, WIN_W, WIN_H, COL_BG)
        if self.box is not None:
            b = self._box()
            b.paint(fb, WIN_W, WIN_H)

    def on_pointer_button(self, x: int, y: int, pressed: int) -> int:
        if pressed and self.box is not None:
            b = self._box()
            return b.press(x, y)
        return ACTION_NONE

    def run(self) -> int:
        set_active(self)
        return _wl.rwl_run()


class QApplication:
    """Minimal QApplication. exec_(win) runs the window's Wayland loop."""

    def __init__(self):
        self.ok = 1

    def exec_(self, win: "obj") -> int:
        return win.run()


# ---- runtime trampolines (called from the generated rwayland_rt.c) -------
_active: "QWidget*" = None


def set_active(w: "QWidget*") -> None:
    global _active
    _active = w


def rw_width() -> int:
    return _active.width


def rw_height() -> int:
    return _active.height


def rw_title() -> "char*":
    return _active.title


def rw_paint(fb: "u32*") -> None:
    _active.on_paint(fb)


def rw_pointer(x: int, y: int, pressed: int) -> int:
    return _active.on_pointer_button(x, y, pressed)
