"""rpyqt -- a restricted, PyQt-compatible widget API built on rwayland.

This is *not* bound to Qt. It is a small emulation layer: enough of the PyQt5
surface (QApplication, QWidget, QLabel, QPushButton, QVBoxLayout, a `clicked`
signal) that PyQt-shaped code transpiles and runs as a native Wayland client,
software-rendered into the rwayland framebuffer. Users who do not want the Qt
shape can drop down to `rwayland` directly.

    from rpyqt import QApplication, QWidget, QVBoxLayout, QLabel, QPushButton

    def main() -> int:
        app = QApplication()
        win = QWidget()
        win.setWindowTitle("counter")
        layout = QVBoxLayout()
        label = QLabel("COUNT 0")
        button = QPushButton("INCREMENT")
        button.clicked.connect(on_click)     # a no-arg handler
        layout.addWidget(label)
        layout.addWidget(button)
        win.setLayout(layout)
        return app.exec_(win)

Rendering: each widget draws itself into the XRGB8888 framebuffer with a built
-in 5x7 bitmap font (uppercase letters, digits, space, and a few symbols). The
rpyqt binds the generated Wayland runtime directly (rwl_run + the rw_* hooks),
so the Wayland glue is machine-generated by py2c -- no C is hand-written.

Scope: vertical layout only; one signal (`clicked`); a no-arg handler. The aim
is to show the adaptation path PyQt -> rpyqt -> Wayland, not API completeness.
"""
import rpy_ctypes as ctypes

# rpyqt is self-contained over the generated Wayland runtime: it binds rwl_run()
# (resolved from rwayland_rt.o at link time) and defines the six rw_* hooks the
# runtime calls. It deliberately does NOT subclass rwayland.Window, so every
# class here is locally rooted and shares one consistent vtable layout -- mixing
# a cross-module-rooted class with local hierarchies in a single module yields
# inconsistent vtables under py2c.
_wl = ctypes.CDLL("libwayland-client.so.0")
_wl.rwl_run.restype = ctypes.c_int
_wl.rwl_run.argtypes = []

ACTION_QUIT = 0
ACTION_MOVE = 1
ACTION_REDRAW = 2
ACTION_NONE = 3


def fill_rect(fb: "u32*", fb_w: int, fb_h: int,
              x: int, y: int, w: int, h: int, color: int) -> None:
    yy = y
    y1 = y + h
    while yy < y1:
        if yy >= 0 and yy < fb_h:
            xx = x
            x1 = x + w
            while xx < x1:
                if xx >= 0 and xx < fb_w:
                    fb[yy * fb_w + xx] = color
                xx = xx + 1
        yy = yy + 1

# ---- geometry / palette --------------------------------------------------
WIN_W = 480
WIN_H = 320
PAD = 16
ROW_H = 44
GAP = 12

COL_BG = 0xFFF0F0F0
COL_LABEL_BG = 0xFFF0F0F0
COL_BTN = 0xFF0088FF
COL_BTN_DOWN = 0xFF005FBF
COL_TEXT = 0xFF202020
COL_BTN_TEXT = 0xFFFFFFFF
COL_ACCENT = 0xFF00AA00      # checkbox tick / slider handle / progress fill
COL_TRACK = 0xFFCFCFCF       # slider / progress groove
COL_BOX = 0xFFFFFFFF         # checkbox box interior
COL_BORDER = 0xFF808080      # widget outlines
COL_LINK = 0xFF0645AD        # anchor / hyperlink text
COL_FIELD = 0xFFFFFFFF       # line-edit interior
COL_HINT = 0xFF909090        # line-edit placeholder text
COL_RULE = 0xFFCCCCCC        # <hr> horizontal rule


# ---- 5x7 bitmap font -----------------------------------------------------
# Each glyph is 7 rows; each row's low 5 bits are pixels (MSB = leftmost).
# Covers A-Z, 0-9, space, ':' and '.'; unknown chars render blank.
def glyph_row(ch: int, row: int) -> int:
    # Letters
    if ch == 65:   # A
        r = [0x0E, 0x11, 0x11, 0x1F, 0x11, 0x11, 0x11]
    elif ch == 66:  # B
        r = [0x1E, 0x11, 0x1E, 0x11, 0x11, 0x11, 0x1E]
    elif ch == 67:  # C
        r = [0x0E, 0x11, 0x10, 0x10, 0x10, 0x11, 0x0E]
    elif ch == 68:  # D
        r = [0x1E, 0x11, 0x11, 0x11, 0x11, 0x11, 0x1E]
    elif ch == 69:  # E
        r = [0x1F, 0x10, 0x1E, 0x10, 0x10, 0x10, 0x1F]
    elif ch == 70:  # F
        r = [0x1F, 0x10, 0x1E, 0x10, 0x10, 0x10, 0x10]
    elif ch == 71:  # G
        r = [0x0E, 0x11, 0x10, 0x17, 0x11, 0x11, 0x0F]
    elif ch == 72:  # H
        r = [0x11, 0x11, 0x1F, 0x11, 0x11, 0x11, 0x11]
    elif ch == 73:  # I
        r = [0x0E, 0x04, 0x04, 0x04, 0x04, 0x04, 0x0E]
    elif ch == 74:  # J
        r = [0x07, 0x02, 0x02, 0x02, 0x12, 0x12, 0x0C]
    elif ch == 75:  # K
        r = [0x11, 0x12, 0x14, 0x18, 0x14, 0x12, 0x11]
    elif ch == 76:  # L
        r = [0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x1F]
    elif ch == 77:  # M
        r = [0x11, 0x1B, 0x15, 0x15, 0x11, 0x11, 0x11]
    elif ch == 78:  # N
        r = [0x11, 0x19, 0x15, 0x13, 0x11, 0x11, 0x11]
    elif ch == 79:  # O
        r = [0x0E, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0E]
    elif ch == 80:  # P
        r = [0x1E, 0x11, 0x11, 0x1E, 0x10, 0x10, 0x10]
    elif ch == 81:  # Q
        r = [0x0E, 0x11, 0x11, 0x11, 0x15, 0x12, 0x0D]
    elif ch == 82:  # R
        r = [0x1E, 0x11, 0x11, 0x1E, 0x14, 0x12, 0x11]
    elif ch == 83:  # S
        r = [0x0F, 0x10, 0x10, 0x0E, 0x01, 0x01, 0x1E]
    elif ch == 84:  # T
        r = [0x1F, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04]
    elif ch == 85:  # U
        r = [0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0E]
    elif ch == 86:  # V
        r = [0x11, 0x11, 0x11, 0x11, 0x11, 0x0A, 0x04]
    elif ch == 87:  # W
        r = [0x11, 0x11, 0x11, 0x15, 0x15, 0x1B, 0x11]
    elif ch == 88:  # X
        r = [0x11, 0x0A, 0x04, 0x04, 0x04, 0x0A, 0x11]
    elif ch == 89:  # Y
        r = [0x11, 0x0A, 0x04, 0x04, 0x04, 0x04, 0x04]
    elif ch == 90:  # Z
        r = [0x1F, 0x01, 0x02, 0x04, 0x08, 0x10, 0x1F]
    elif ch == 48:  # 0
        r = [0x0E, 0x11, 0x13, 0x15, 0x19, 0x11, 0x0E]
    elif ch == 49:  # 1
        r = [0x04, 0x0C, 0x04, 0x04, 0x04, 0x04, 0x0E]
    elif ch == 50:  # 2
        r = [0x0E, 0x11, 0x01, 0x02, 0x04, 0x08, 0x1F]
    elif ch == 51:  # 3
        r = [0x1F, 0x02, 0x04, 0x02, 0x01, 0x11, 0x0E]
    elif ch == 52:  # 4
        r = [0x02, 0x06, 0x0A, 0x12, 0x1F, 0x02, 0x02]
    elif ch == 53:  # 5
        r = [0x1F, 0x10, 0x1E, 0x01, 0x01, 0x11, 0x0E]
    elif ch == 54:  # 6
        r = [0x06, 0x08, 0x10, 0x1E, 0x11, 0x11, 0x0E]
    elif ch == 55:  # 7
        r = [0x1F, 0x01, 0x02, 0x04, 0x08, 0x08, 0x08]
    elif ch == 56:  # 8
        r = [0x0E, 0x11, 0x11, 0x0E, 0x11, 0x11, 0x0E]
    elif ch == 57:  # 9
        r = [0x0E, 0x11, 0x11, 0x0F, 0x01, 0x02, 0x0C]
    elif ch == 58:  # :
        r = [0x00, 0x04, 0x00, 0x00, 0x00, 0x04, 0x00]
    elif ch == 46:  # .
        r = [0x00, 0x00, 0x00, 0x00, 0x00, 0x0C, 0x0C]
    elif ch == 45:  # -
        r = [0x00, 0x00, 0x00, 0x1F, 0x00, 0x00, 0x00]
    elif ch == 47:  # /
        r = [0x01, 0x02, 0x02, 0x04, 0x08, 0x08, 0x10]
    elif ch == 63:  # ?
        r = [0x0E, 0x11, 0x01, 0x02, 0x04, 0x00, 0x04]
    elif ch == 33:  # !
        r = [0x04, 0x04, 0x04, 0x04, 0x04, 0x00, 0x04]
    elif ch == 61:  # =
        r = [0x00, 0x00, 0x1F, 0x00, 0x1F, 0x00, 0x00]
    elif ch == 44:  # ,
        r = [0x00, 0x00, 0x00, 0x00, 0x00, 0x0C, 0x04]
    elif ch == 40:  # (
        r = [0x02, 0x04, 0x08, 0x08, 0x08, 0x04, 0x02]
    elif ch == 41:  # )
        r = [0x08, 0x04, 0x02, 0x02, 0x02, 0x04, 0x08]
    elif ch == 35:  # #
        r = [0x0A, 0x0A, 0x1F, 0x0A, 0x1F, 0x0A, 0x0A]
    else:           # space / unknown
        r = [0, 0, 0, 0, 0, 0, 0]
    return r[row]


def draw_char(fb: "u32*", fbw: int, fbh: int, x: int, y: int,
              ch: int, scale: int, color: int) -> None:
    # The 5x7 font only carries uppercase glyphs; fold lowercase onto them so
    # ordinary web text (mostly lowercase) is legible without a second table.
    if ch >= 97 and ch <= 122:
        ch = ch - 32
    row = 0
    while row < 7:
        bits = glyph_row(ch, row)
        col = 0
        while col < 5:
            on = (bits >> (4 - col)) & 1
            if on:
                fill_rect(fb, fbw, fbh,
                                   x + col * scale, y + row * scale,
                                   scale, scale, color)
            col = col + 1
        row = row + 1


def draw_text(fb: "u32*", fbw: int, fbh: int, x: int, y: int,
              text: "char*", scale: int, color: int) -> None:
    n = len(text)
    i = 0
    cx = x
    while i < n:
        draw_char(fb, fbw, fbh, cx, y, ord(text[i]), scale, color)
        cx = cx + 6 * scale
        i = i + 1


def _draw_border(fb: "u32*", x: int, y: int, w: int, h: int, color: int) -> None:
    fill_rect(fb, WIN_W, WIN_H, x, y, w, 2, color)
    fill_rect(fb, WIN_W, WIN_H, x, y + h - 2, w, 2, color)
    fill_rect(fb, WIN_W, WIN_H, x, y, 2, h, color)
    fill_rect(fb, WIN_W, WIN_H, x + w - 2, y, 2, h, color)


# ---- universal base ------------------------------------------------------
class _QtObject:
    """Root of every rpyqt class. Carries the geometry (x/y/w/h) and the
    place()/paint()/on_press() interface shared by BOTH widgets and layouts, so
    a layout can hold a heterogeneous list of children (widgets or nested
    layouts) and position, paint, and hit-test them uniformly through one
    consistent vtable. A single local root also avoids cross-module vtable-canon
    pinning, keeping VT_rpyqt identical on the defining and importing side."""

    def __init__(self):
        self.x = 0
        self.y = 0
        self.w = 0
        self.h = 0

    def place(self, x: int, y: int, w: int, h: int) -> None:
        self.x = x
        self.y = y
        self.w = w
        self.h = h

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        return

    def pref_h(self) -> int:
        # Preferred row height for the vertical layout; widgets that need a
        # specific height (e.g. a canvas) override this.
        return ROW_H

    def contains(self, px: int, py: int) -> int:
        # Hit-test against this object's own geometry. Done as a method (read on
        # the concrete self) so a parent layout never reads x/y/w/h through an
        # obj-typed child reference -- which would force those fields to be
        # boxed (obj) instead of plain int.
        if px >= self.x and px < self.x + self.w \
                and py >= self.y and py < self.y + self.h:
            return 1
        return 0

    def on_press(self, px: int, py: int) -> int:
        return ACTION_NONE

    def on_key(self, codepoint: int, pressed: int) -> int:
        # Overridden by editable widgets (QLineEdit). Declared on the base so a
        # key routed through an obj-typed focus reference dispatches virtually.
        return ACTION_NONE

    def set_focused(self, v: int) -> None:
        # Overridden by focusable widgets; a no-op elsewhere so focus bookkeeping
        # can call it uniformly through an obj reference.
        return


# ---- signal --------------------------------------------------------------
class Signal(_QtObject):
    """A one-slot signal: connect(fn) stores a no-arg handler, emit() calls it.
    PyQt slots that take a value can instead read the widget's state on demand
    (e.g. slider.value()), keeping the generated FFI simple. Object-model (via
    _QtObject) so connect/emit are real vtable slots on both module sides."""

    def __init__(self):
        super().__init__()
        self.handler = None

    def connect(self, fn: "obj") -> None:
        self.handler = fn

    def emit(self) -> None:
        f = self.handler
        if f is not None:
            f()


# ---- widgets -------------------------------------------------------------
class Widget(_QtObject):
    """Base child widget. Geometry is assigned by the parent layout via place().
    The value/setValue/isChecked/setChecked accessors are declared here (not
    only on the leaf widgets) so a call through an obj-typed reference -- e.g. a
    widget stored in a slot/global -- dispatches virtually."""

    def __init__(self):
        super().__init__()
        self.text = ""
        self.action = ""        # e.g. an HTML onclick handler ("foo()")

    def setText(self, text: "char*") -> None:
        self.text = text

    def set_action(self, a: "char*") -> None:
        self.action = a

    def action_value(self) -> "char*":
        return self.action

    def text_value(self) -> "char*":
        # Declared on the base so a widget reached through an obj reference (a
        # focused field, an activated link) can be read back uniformly.
        return self.text

    def href_value(self) -> "char*":
        # Navigation target of an anchor; overridden by QLink, "" elsewhere.
        # Named href_value (not get_href) to avoid colliding with the DOM
        # Node.get_href in the co-compiled minibrowser: a shared method name
        # across the two class hierarchies makes obj-dispatch pick the wrong
        # vtable.
        return ""

    def value(self) -> int:
        return 0

    def setValue(self, v: int) -> None:
        return

    def isChecked(self) -> int:
        return 0

    def setChecked(self, v: int) -> None:
        return


class QLabel(Widget):
    def __init__(self, text: "char*"):
        super().__init__()
        self.text = text

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_LABEL_BG)
        draw_text(fb, fbw, fbh, self.x + 8, self.y + 14, self.text, 3, COL_TEXT)


class QPushButton(Widget):
    def __init__(self, text: "char*"):
        super().__init__()
        self.text = text
        self.clicked = Signal()

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_BTN)
        draw_text(fb, fbw, fbh, self.x + 12, self.y + 14, self.text, 3,
                  COL_BTN_TEXT)

    def on_press(self, px: int, py: int) -> int:
        if len(self.action) > 0:
            set_last_action(self.action)
        self.clicked.emit()
        return ACTION_REDRAW


class QHeading(Widget):
    """A heading label (h1-h6). `level` selects a font scale so h1 renders
    largest; deeper levels fall back to the body scale. Bold is approximated by
    the larger glyph size (the 5x7 font has no weight axis)."""

    def __init__(self, text: "char*", level: int):
        super().__init__()
        self.text = text
        if level <= 1:
            self.scale = 5
        elif level == 2:
            self.scale = 4
        else:
            self.scale = 3

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_LABEL_BG)
        draw_text(fb, fbw, fbh, self.x + 4, self.y + 8, self.text, self.scale,
                  COL_TEXT)


class QLink(Widget):
    """An anchor: link-coloured, underlined text that emits `clicked` when
    pressed. `href` is the navigation target; on press the link records itself
    as the last-activated link (so a no-arg `clicked` handler can recover the
    href via `last_link_href()`) and fires `clicked`."""

    def __init__(self, text: "char*", href: "char*"):
        super().__init__()
        self.text = text
        self.href = href
        self.clicked = Signal()

    def href_value(self) -> "char*":
        return self.href

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_LABEL_BG)
        draw_text(fb, fbw, fbh, self.x + 8, self.y + 14, self.text, 3, COL_LINK)
        # underline
        n = len(self.text)
        fill_rect(fb, fbw, fbh, self.x + 8, self.y + 14 + 22, n * 18, 2,
                  COL_LINK)

    def on_press(self, px: int, py: int) -> int:
        set_last_link(self)
        self.clicked.emit()
        return ACTION_REDRAW


class QLineEdit(Widget):
    """A single-line text field. It renders its current text (or a greyed
    placeholder when empty) inside a bordered box, with a caret and a
    highlighted border while focused. Clicking the field gives it keyboard
    focus; keys are routed here by the top-level window via on_key(). A press
    also focuses, and Enter emits `returnPressed` (submit)."""

    def __init__(self, text: "char*"):
        super().__init__()
        self.text = text
        self.placeholder = ""
        self.focused = 0
        self.returnPressed = Signal()

    def setPlaceholderText(self, text: "char*") -> None:
        self.placeholder = text

    def text_value(self) -> "char*":
        return self.text

    def set_focused(self, v: int) -> None:
        self.focused = v

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_FIELD)
        if self.focused:
            _draw_border(fb, self.x, self.y, self.w, self.h, COL_LINK)
        else:
            _draw_border(fb, self.x, self.y, self.w, self.h, COL_BORDER)
        n = len(self.text)
        if n > 0:
            draw_text(fb, fbw, fbh, self.x + 8, self.y + 14, self.text, 3,
                      COL_TEXT)
        else:
            draw_text(fb, fbw, fbh, self.x + 8, self.y + 14, self.placeholder,
                      3, COL_HINT)
        if self.focused:
            # caret just past the end of the text (6*scale px per glyph)
            cx = self.x + 8 + n * 18
            fill_rect(fb, fbw, fbh, cx, self.y + 12, 2, 24, COL_TEXT)

    def on_press(self, px: int, py: int) -> int:
        set_focus(self)
        return ACTION_REDRAW

    def on_key(self, codepoint: int, pressed: int) -> int:
        if not pressed:
            return ACTION_NONE
        if codepoint == 8:                      # backspace
            n = len(self.text)
            if n > 0:
                self.text = self.text[0:n - 1]
            return ACTION_REDRAW
        if codepoint == 13:                     # enter -> submit
            self.returnPressed.emit()
            return ACTION_REDRAW
        if codepoint >= 32:                     # printable -> append
            self.text = self.text + chr(codepoint)
            return ACTION_REDRAW
        return ACTION_NONE


class QHLine(Widget):
    """A horizontal rule (<hr>): a thin centred line across the row."""

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_BG)
        ty = self.y + self.h // 2 - 1
        fill_rect(fb, fbw, fbh, self.x, ty, self.w, 2, COL_RULE)


class QCanvas(Widget):
    """A pixel surface: holds a cw*ch list of packed ARGB pixels and blits them
    into the framebuffer. The pixels are produced by native code (a JIT-compiled
    <script type="rpython"> shader called per pixel), so this widget is how that
    native output reaches the page -- the browser's Canvas primitive."""

    def __init__(self, cw: int, ch: int):
        super().__init__()
        self.cw = cw
        self.ch = ch
        self.px: "list[int]" = []       # cw*ch packed ARGB pixels

    def set_pixels(self, px: "list[int]") -> None:
        self.px = px

    def pref_h(self) -> int:
        return self.ch

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        n = len(self.px)
        cw = self.cw
        j = 0
        while j < n:
            col: "int" = self.px[j]
            fx: "int" = self.x + (j % cw)
            fy: "int" = self.y + (j // cw)
            if fx >= 0 and fx < fbw and fy >= 0 and fy < fbh:
                fb[fy * fbw + fx] = col
            j = j + 1


class QCheckBox(Widget):
    """A labelled checkbox; clicking toggles it and emits stateChanged."""

    def __init__(self, text: "char*"):
        super().__init__()
        self.text = text
        self.checked = 0
        self.stateChanged = Signal()

    def isChecked(self) -> int:
        return self.checked

    def setChecked(self, v: int) -> None:
        self.checked = v

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_BG)
        bs = 28
        by = self.y + (self.h - bs) // 2
        fill_rect(fb, fbw, fbh, self.x, by, bs, bs, COL_BOX)
        _draw_border(fb, self.x, by, bs, bs, COL_BORDER)
        if self.checked:
            fill_rect(fb, fbw, fbh, self.x + 6, by + 6, bs - 12, bs - 12,
                      COL_ACCENT)
        draw_text(fb, fbw, fbh, self.x + bs + 12, self.y + 14, self.text, 3,
                  COL_TEXT)

    def on_press(self, px: int, py: int) -> int:
        if self.checked:
            self.checked = 0
        else:
            self.checked = 1
        self.stateChanged.emit()
        return ACTION_REDRAW


class QSlider(Widget):
    """A horizontal slider with an integer value in [0, 100]. Clicking sets the
    value from the click x-position and emits valueChanged."""

    def __init__(self):
        super().__init__()
        self._val = 0
        self.valueChanged = Signal()

    def value(self) -> int:
        return self._val

    def setValue(self, v: int) -> None:
        if v < 0:
            v = 0
        if v > 100:
            v = 100
        self._val = v

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_BG)
        ty = self.y + self.h // 2 - 3
        fill_rect(fb, fbw, fbh, self.x, ty, self.w, 6, COL_TRACK)
        hx = self.x + (self._val * (self.w - 16)) // 100
        fill_rect(fb, fbw, fbh, hx, self.y + 4, 16, self.h - 8, COL_ACCENT)

    def on_press(self, px: int, py: int) -> int:
        rel = px - self.x
        v = (rel * 100) // self.w
        self.setValue(v)
        self.valueChanged.emit()
        return ACTION_REDRAW


class QProgressBar(Widget):
    """A display-only bar showing an integer value in [0, 100]."""

    def __init__(self):
        super().__init__()
        self._val = 0

    def value(self) -> int:
        return self._val

    def setValue(self, v: int) -> None:
        if v < 0:
            v = 0
        if v > 100:
            v = 100
        self._val = v

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        fill_rect(fb, fbw, fbh, self.x, self.y, self.w, self.h, COL_TRACK)
        fw = (self._val * self.w) // 100
        fill_rect(fb, fbw, fbh, self.x, self.y, fw, self.h, COL_ACCENT)
        _draw_border(fb, self.x, self.y, self.w, self.h, COL_BORDER)


# ---- layouts (also _QtObject, so they nest like widgets) -----------------
class QBoxLayout(_QtObject):
    """Holds child items (widgets OR nested layouts) and paints / hit-tests them
    through the shared place()/paint()/on_press() interface. Subclasses override
    place() to assign child geometry (vertical or horizontal)."""

    def __init__(self):
        super().__init__()
        self.items: "list[obj]" = []

    def addWidget(self, w: "obj") -> None:
        self.items.append(w)

    def addLayout(self, lay: "obj") -> None:
        self.items.append(lay)

    def count(self) -> int:
        return len(self.items)

    def paint(self, fb: "u32*", fbw: int, fbh: int) -> None:
        i = 0
        n = len(self.items)
        while i < n:
            self.items[i].paint(fb, fbw, fbh)
            i = i + 1

    def on_press(self, px: int, py: int) -> int:
        i = 0
        n = len(self.items)
        while i < n:
            c = self.items[i]
            if c.contains(px, py):
                return c.on_press(px, py)
            i = i + 1
        return ACTION_NONE


class QVBoxLayout(QBoxLayout):
    """Stack children top-to-bottom, each full width, fixed row height."""

    def place(self, x: int, y: int, w: int, h: int) -> None:
        self.x = x
        self.y = y
        self.w = w
        self.h = h
        cy = y
        i = 0
        n = len(self.items)
        while i < n:
            rh: "int" = self.items[i].pref_h()
            self.items[i].place(x, cy, w, rh)
            cy = cy + rh + GAP
            i = i + 1


class QHBoxLayout(QBoxLayout):
    """Place children left-to-right in equal-width columns, full row height."""

    def place(self, x: int, y: int, w: int, h: int) -> None:
        self.x = x
        self.y = y
        self.w = w
        self.h = h
        n = len(self.items)
        if n == 0:
            return
        cw = (w - (n - 1) * GAP) // n
        cx = x
        i = 0
        while i < n:
            self.items[i].place(cx, y, cw, h)
            cx = cx + cw + GAP
            i = i + 1


# ---- top-level window ----------------------------------------------------
class QWidget(_QtObject):
    """A top-level window hosting one layout. Painted / pointer-routed by the
    module-level rw_* trampolines the generated runtime calls. The layout is
    dispatched virtually, so any QBoxLayout subclass works."""

    def __init__(self):
        super().__init__()
        self.box = None
        self.title = "rpyqt"
        self.width = WIN_W
        self.height = WIN_H

    def setWindowTitle(self, title: "char*") -> None:
        self.title = title

    def setLayout(self, box: "QBoxLayout") -> None:
        # The argument is always a layout (a QBoxLayout subclass), so it is typed
        # concretely rather than as obj: that passes a plain pointer instead of a
        # 16-byte boxed value, which is what lets setLayout be called on a window
        # held in a module global (e.g. re-layout during navigation) without the
        # untyped-extern arg mis-lowering that a boxed obj would hit.
        self.box = box
        box.place(PAD, PAD, WIN_W - 2 * PAD, WIN_H - 2 * PAD)

    def on_paint(self, fb: "u32*") -> None:
        fill_rect(fb, WIN_W, WIN_H, 0, 0, WIN_W, WIN_H, COL_BG)
        b = self.box
        if b is not None:
            b.paint(fb, WIN_W, WIN_H)

    def on_pointer_button(self, x: int, y: int, pressed: int) -> int:
        b = self.box
        if pressed and b is not None:
            return b.on_press(x, y)
        return ACTION_NONE

    def on_key(self, codepoint: int, pressed: int) -> int:
        f = _focused
        if f is not None:
            return f.on_key(codepoint, pressed)
        return ACTION_NONE

    def run(self) -> int:
        set_active(self)
        return _wl.rwl_run()


class QApplication(_QtObject):
    """Minimal QApplication. exec_(win) runs the window's Wayland loop."""

    def __init__(self):
        super().__init__()
        self.ok = 1

    def exec_(self, win: "obj") -> int:
        return win.run()


# ---- runtime trampolines (called from the generated rwayland_rt.c) -------
_active: "QWidget*" = None
# The widget currently holding keyboard focus (a QLineEdit), or None. Clicking a
# field focuses it; the window routes keys here. Kept as a module global (like
# _active) so focus is process-wide and reachable from the rw_key trampoline.
_focused = None


def set_active(w: "QWidget*") -> None:
    global _active
    _active = w


def set_focus(w: "obj") -> None:
    global _focused
    prev = _focused
    if prev is not None:
        prev.set_focused(0)
    _focused = w
    w.set_focused(1)


# The most recently activated QLink. Recorded on press so a no-arg `clicked`
# handler can recover the navigation target with last_link_href().
_last_link = None


def set_last_link(w: "obj") -> None:
    global _last_link
    _last_link = w


def last_link_href() -> "char*":
    w = _last_link
    if w is not None:
        return w.href_value()
    return ""


# The action string (e.g. an HTML onclick like "foo()") of the most recently
# pressed widget that carried one. A no-arg `clicked` handler recovers it with
# last_action() to decide which script function to invoke.
_last_action = ""


def set_last_action(a: "char*") -> None:
    global _last_action
    _last_action = a


def last_action() -> "char*":
    return _last_action


def rw_width() -> int:
    return _active.width


def rw_height() -> int:
    return _active.height


def rw_title() -> "char*":
    return _active.title


def rw_paint(fb: "u32*") -> None:
    _active.on_paint(fb)


def rw_pointer(x: int, y: int, pressed: int) -> int:
    return _active.on_pointer_button(x, y, pressed)


def rw_key(codepoint: int, pressed: int) -> int:
    return _active.on_key(codepoint, pressed)
