"""Layout metadata for the packaged musl tree (auto-generated)."""

CATEGORIES = [
    ('aio', 'aio', 3),
    ('complex', 'complex', 68),
    ('conf', 'conf', 5),
    ('crypt', 'crypt', 8),
    ('ctype', 'ctype', 37),
    ('dirent', 'dirent', 13),
    ('env', 'env', 11),
    ('errno', 'errno', 2),
    ('exit', 'exit', 9),
    ('fcntl', 'fcntl', 6),
    ('fenv', 'fenv', 19),
    ('internal', 'internal', 11),
    ('ipc', 'ipc', 13),
    ('ldso', 'ldso', 10),
    ('legacy', 'legacy', 16),
    ('linux', 'linux', 68),
    ('locale', 'locale', 26),
    ('malloc', 'malloc', 18),
    ('math', 'math', 392),
    ('misc', 'misc', 39),
    ('mman', 'mman', 13),
    ('mq', 'mq', 12),
    ('multibyte', 'multibyte', 20),
    ('network', 'network', 77),
    ('passwd', 'passwd', 20),
    ('prng', 'prng', 11),
    ('process', 'process', 34),
    ('regex', 'regex', 6),
    ('sched', 'sched', 10),
    ('search', 'search', 8),
    ('select', 'select', 4),
    ('setjmp', 'setjmp', 2),
    ('signal', 'signal', 40),
    ('stat', 'stat', 20),
    ('stdio', 'stdio', 116),
    ('stdlib', 'stdlib', 22),
    ('string', 'string', 74),
    ('temp', 'temp', 7),
    ('termios', 'termios', 13),
    ('thread', 'thread', 134),
    ('time', 'time', 40),
    ('unistd', 'unistd', 81),
]

PUBLIC_HEADER_DIRS = ['arch/x86_64', 'arch/generic', 'obj/include', 'include']
INTERNAL_HEADER_DIRS = ['obj/src/internal', 'src/include', 'src/internal']
DEFAULT_DEFINES = ['_XOPEN_SOURCE=700']
