"""Packaged musl source: src/fenv/*.c (auto-generated by tools/pack_musl.py; do not edit by hand)."""

CATEGORY = 'fenv'

FILES = {
    '__flt_rounds.c': r'''#include <float.h>
#include <fenv.h>

int __flt_rounds()
{
	switch (fegetround()) {
#ifdef FE_TOWARDZERO
	case FE_TOWARDZERO: return 0;
#endif
	case FE_TONEAREST: return 1;
#ifdef FE_UPWARD
	case FE_UPWARD: return 2;
#endif
#ifdef FE_DOWNWARD
	case FE_DOWNWARD: return 3;
#endif
	}
	return -1;
}
''',
    'fegetexceptflag.c': r'''#include <fenv.h>

int fegetexceptflag(fexcept_t *fp, int mask)
{
	*fp = fetestexcept(mask);
	return 0;
}
''',
    'feholdexcept.c': r'''#include <fenv.h>

int feholdexcept(fenv_t *envp)
{
	fegetenv(envp);
	feclearexcept(FE_ALL_EXCEPT);
	return 0;
}
''',
    'fenv.c': r'''#include <fenv.h>

/* Dummy functions for archs lacking fenv implementation */

int feclearexcept(int mask)
{
	return 0;
}

int feraiseexcept(int mask)
{
	return 0;
}

int fetestexcept(int mask)
{
	return 0;
}

int fegetround(void)
{
	return FE_TONEAREST;
}

int __fesetround(int r)
{
	return 0;
}

int fegetenv(fenv_t *envp)
{
	return 0;
}

int fesetenv(const fenv_t *envp)
{
	return 0;
}
''',
    'fesetexceptflag.c': r'''#include <fenv.h>

int fesetexceptflag(const fexcept_t *fp, int mask)
{
	feclearexcept(~*fp & mask);
	feraiseexcept(*fp & mask);
	return 0;
}
''',
    'fesetround.c': r'''#include <fenv.h>
#include <features.h>

/* __fesetround wrapper for arch independent argument check */

hidden int __fesetround(int);

int fesetround(int r)
{
	if (r != FE_TONEAREST
#ifdef FE_DOWNWARD
		&& r != FE_DOWNWARD
#endif
#ifdef FE_UPWARD
		&& r != FE_UPWARD
#endif
#ifdef FE_TOWARDZERO
		&& r != FE_TOWARDZERO
#endif
	)
		return -1;
	return __fesetround(r);
}
''',
    'feupdateenv.c': r'''#include <fenv.h>

int feupdateenv(const fenv_t *envp)
{
	int ex = fetestexcept(FE_ALL_EXCEPT);
	fesetenv(envp);
	feraiseexcept(ex);
	return 0;
}
''',
    'powerpc64/fenv.c': r'''#define _GNU_SOURCE
#include <fenv.h>
#include <features.h>

static inline double get_fpscr_f(void)
{
	double d;
	__asm__ __volatile__("mffs %0" : "=d"(d));
	return d;
}

static inline long get_fpscr(void)
{
	return (union {double f; long i;}) {get_fpscr_f()}.i;
}

static inline void set_fpscr_f(double fpscr)
{
	__asm__ __volatile__("mtfsf 255, %0" : : "d"(fpscr));
}

static void set_fpscr(long fpscr)
{
	set_fpscr_f((union {long i; double f;}) {fpscr}.f);
}

int feclearexcept(int mask)
{
	mask &= FE_ALL_EXCEPT;
	if (mask & FE_INVALID) mask |= FE_ALL_INVALID;
	set_fpscr(get_fpscr() & ~mask);
	return 0;
}

int feraiseexcept(int mask)
{
	mask &= FE_ALL_EXCEPT;
	if (mask & FE_INVALID) mask |= FE_INVALID_SOFTWARE;
	set_fpscr(get_fpscr() | mask);
	return 0;
}

int fetestexcept(int mask)
{
	return get_fpscr() & mask & FE_ALL_EXCEPT;
}

int fegetround(void)
{
	return get_fpscr() & 3;
}

hidden int __fesetround(int r)
{
	set_fpscr(get_fpscr() & ~3L | r);
	return 0;
}

int fegetenv(fenv_t *envp)
{
	*envp = get_fpscr_f();
	return 0;
}

int fesetenv(const fenv_t *envp)
{
	set_fpscr_f(envp != FE_DFL_ENV ? *envp : 0);
	return 0;
}
''',
    'riscv64/fenv-sf.c': r'''#ifndef __riscv_flen
#include "../fenv.c"
#endif
''',
    'riscv32/fenv-sf.c': r'''#ifndef __riscv_flen
#include "../fenv.c"
#endif
''',
    'sh/fenv-nofpu.c': r'''#if !__SH_FPU_ANY__ && !__SH4__
#include "../fenv.c"
#endif
''',
    'mips/fenv-sf.c': r'''#ifdef __mips_soft_float
#include "../fenv.c"
#endif
''',
    's390x/fenv.c': r'''#include <fenv.h>
#include <features.h>

static inline unsigned get_fpc(void)
{
	unsigned fpc;
	__asm__ __volatile__("efpc %0" : "=r"(fpc));
	return fpc;
}

static inline void set_fpc(unsigned fpc)
{
	__asm__ __volatile__("sfpc %0" :: "r"(fpc));
}

int feclearexcept(int mask)
{
	mask &= FE_ALL_EXCEPT;
	set_fpc(get_fpc() & ~mask);
	return 0;
}

int feraiseexcept(int mask)
{
	mask &= FE_ALL_EXCEPT;
	set_fpc(get_fpc() | mask);
	return 0;
}

int fetestexcept(int mask)
{
	return get_fpc() & mask & FE_ALL_EXCEPT;
}

int fegetround(void)
{
	return get_fpc() & 3;
}

hidden int __fesetround(int r)
{
	set_fpc(get_fpc() & ~3L | r);
	return 0;
}

int fegetenv(fenv_t *envp)
{
	*envp = get_fpc();
	return 0;
}

int fesetenv(const fenv_t *envp)
{
	set_fpc(envp != FE_DFL_ENV ? *envp : 0);
	return 0;
}
''',
    'loongarch64/fenv-sf.c': r'''#ifdef __loongarch_soft_float
#include "../fenv.c"
#endif
''',
    'm68k/fenv.c': r'''#include <fenv.h>
#include <features.h>

#if __HAVE_68881__ || __mcffpu__

static unsigned getsr()
{
	unsigned v;
	__asm__ __volatile__ ("fmove.l %%fpsr,%0" : "=dm"(v));
	return v;
}

static void setsr(unsigned v)
{
	__asm__ __volatile__ ("fmove.l %0,%%fpsr" : : "dm"(v));
}

static unsigned getcr()
{
	unsigned v;
	__asm__ __volatile__ ("fmove.l %%fpcr,%0" : "=dm"(v));
	return v;
}

static void setcr(unsigned v)
{
	__asm__ __volatile__ ("fmove.l %0,%%fpcr" : : "dm"(v));
}

int feclearexcept(int mask)
{
	if (mask & ~FE_ALL_EXCEPT) return -1;
	setsr(getsr() & ~mask);
	return 0;
}

int feraiseexcept(int mask)
{
	if (mask & ~FE_ALL_EXCEPT) return -1;
	setsr(getsr() | mask);
	return 0;
}

int fetestexcept(int mask)
{
	return getsr() & mask;
}

int fegetround(void)
{
	return getcr() & FE_UPWARD;
}

hidden int __fesetround(int r)
{
	setcr((getcr() & ~FE_UPWARD) | r);
	return 0;
}

int fegetenv(fenv_t *envp)
{
	envp->__control_register = getcr();
	envp->__status_register = getsr();
	__asm__ __volatile__ ("fmove.l %%fpiar,%0"
		: "=dm"(envp->__instruction_address));
	return 0;
}

int fesetenv(const fenv_t *envp)
{
	static const fenv_t default_env = { 0 };
	if (envp == FE_DFL_ENV)
		envp = &default_env;
	setcr(envp->__control_register);
	setsr(envp->__status_register);
	__asm__ __volatile__ ("fmove.l %0,%%fpiar"
		: : "dm"(envp->__instruction_address));
	return 0;
}

#else

#include "../fenv.c"

#endif
''',
    'powerpc/fenv-sf.c': r'''#if defined(_SOFT_FLOAT) || defined(__NO_FPRS__)
#include "../fenv.c"
#endif
''',
    'arm/fenv.c': r'''#if !__ARM_PCS_VFP
#include "../fenv.c"
#endif
''',
    'mips64/fenv-sf.c': r'''#ifdef __mips_soft_float
#include "../fenv.c"
#endif
''',
    'mipsn32/fenv-sf.c': r'''#ifdef __mips_soft_float
#include "../fenv.c"
#endif
''',
}
