"""Packaged musl source: src/ldso/*.c (auto-generated by tools/pack_musl.py; do not edit by hand)."""

CATEGORY = 'ldso'

FILES = {
    '__dlsym.c': r'''#include <dlfcn.h>
#include "dynlink.h"

static void *stub_dlsym(void *restrict p, const char *restrict s, void *restrict ra)
{
	__dl_seterr("Symbol not found: %s", s);
	return 0;
}

weak_alias(stub_dlsym, __dlsym);

#if _REDIR_TIME64
weak_alias(stub_dlsym, __dlsym_redir_time64);
#endif
''',
    'dl_iterate_phdr.c': r'''#include <elf.h>
#include <link.h>
#include "pthread_impl.h"
#include "libc.h"

#define AUX_CNT 38

extern weak hidden const size_t _DYNAMIC[];

static int static_dl_iterate_phdr(int(*callback)(struct dl_phdr_info *info, size_t size, void *data), void *data)
{
	unsigned char *p;
	ElfW(Phdr) *phdr, *tls_phdr=0;
	size_t base = 0;
	size_t n;
	struct dl_phdr_info info;
	size_t i, aux[AUX_CNT] = {0};

	for (i=0; libc.auxv[i]; i+=2)
		if (libc.auxv[i]<AUX_CNT) aux[libc.auxv[i]] = libc.auxv[i+1];

	for (p=(void *)aux[AT_PHDR],n=aux[AT_PHNUM]; n; n--,p+=aux[AT_PHENT]) {
		phdr = (void *)p;
		if (phdr->p_type == PT_PHDR)
			base = aux[AT_PHDR] - phdr->p_vaddr;
		if (phdr->p_type == PT_DYNAMIC && _DYNAMIC)
			base = (size_t)_DYNAMIC - phdr->p_vaddr;
		if (phdr->p_type == PT_TLS)
			tls_phdr = phdr;
	}
	info.dlpi_addr  = base;
	info.dlpi_name  = "/proc/self/exe";
	info.dlpi_phdr  = (void *)aux[AT_PHDR];
	info.dlpi_phnum = aux[AT_PHNUM];
	info.dlpi_adds  = 0;
	info.dlpi_subs  = 0;
	if (tls_phdr) {
		info.dlpi_tls_modid = 1;
		info.dlpi_tls_data = __tls_get_addr((tls_mod_off_t[]){1,0});
	} else {
		info.dlpi_tls_modid = 0;
		info.dlpi_tls_data = 0;
	}
	return (callback)(&info, sizeof (info), data);
}

weak_alias(static_dl_iterate_phdr, dl_iterate_phdr);
''',
    'dladdr.c': r'''#define _GNU_SOURCE
#include <dlfcn.h>

static int stub_dladdr(const void *addr, Dl_info *info)
{
	return 0;
}

weak_alias(stub_dladdr, dladdr);
''',
    'dlclose.c': r'''#include <dlfcn.h>
#include "dynlink.h"

int dlclose(void *p)
{
	return __dl_invalid_handle(p);
}
''',
    'dlerror.c': r'''#include <dlfcn.h>
#include <stdlib.h>
#include <stdarg.h>
#include "pthread_impl.h"
#include "dynlink.h"
#include "atomic.h"

#define malloc __libc_malloc
#define calloc __libc_calloc
#define realloc __libc_realloc
#define free __libc_free

char *dlerror()
{
	pthread_t self = __pthread_self();
	if (!self->dlerror_flag) return 0;
	self->dlerror_flag = 0;
	char *s = self->dlerror_buf;
	if (s == (void *)-1)
		return "Dynamic linker failed to allocate memory for error message";
	else
		return s;
}

/* Atomic singly-linked list, used to store list of thread-local dlerror
 * buffers for deferred free. They cannot be freed at thread exit time
 * because, by the time it's known they can be freed, the exiting thread
 * is in a highly restrictive context where it cannot call (even the
 * libc-internal) free. It also can't take locks; thus the atomic list. */

static void *volatile freebuf_queue;

void __dl_thread_cleanup(void)
{
	pthread_t self = __pthread_self();
	if (!self->dlerror_buf || self->dlerror_buf == (void *)-1)
		return;
	void *h;
	do {
		h = freebuf_queue;
		*(void **)self->dlerror_buf = h;
	} while (a_cas_p(&freebuf_queue, h, self->dlerror_buf) != h);
}

hidden void __dl_vseterr(const char *fmt, va_list ap)
{
	void **q;
	do q = freebuf_queue;
	while (q && a_cas_p(&freebuf_queue, q, 0) != q);

	while (q) {
		void **p = *q;
		free(q);
		q = p;
	}

	va_list ap2;
	va_copy(ap2, ap);
	pthread_t self = __pthread_self();
	if (self->dlerror_buf != (void *)-1)
		free(self->dlerror_buf);
	size_t len = vsnprintf(0, 0, fmt, ap2);
	if (len < sizeof(void *)) len = sizeof(void *);
	va_end(ap2);
	char *buf = malloc(len+1);
	if (buf) {
		vsnprintf(buf, len+1, fmt, ap);
	} else {
		buf = (void *)-1;	
	}
	self->dlerror_buf = buf;
	self->dlerror_flag = 1;
}

hidden void __dl_seterr(const char *fmt, ...)
{
	va_list ap;
	va_start(ap, fmt);
	__dl_vseterr(fmt, ap);
	va_end(ap);
}

static int stub_invalid_handle(void *h)
{
	__dl_seterr("Invalid library handle %p", (void *)h);
	return 1;
}

weak_alias(stub_invalid_handle, __dl_invalid_handle);
''',
    'dlinfo.c': r'''#define _GNU_SOURCE
#include <dlfcn.h>
#include "dynlink.h"

int dlinfo(void *dso, int req, void *res)
{
	if (__dl_invalid_handle(dso)) return -1;
	if (req != RTLD_DI_LINKMAP) {
		__dl_seterr("Unsupported request %d", req);
		return -1;
	}
	*(struct link_map **)res = dso;
	return 0;
}
''',
    'dlopen.c': r'''#include <dlfcn.h>
#include "dynlink.h"

static void *stub_dlopen(const char *file, int mode)
{
	__dl_seterr("Dynamic loading not supported");
	return 0;
}

weak_alias(stub_dlopen, dlopen);
''',
    'dlsym.c': r'''#include <dlfcn.h>
#include "dynlink.h"

void *dlsym(void *restrict p, const char *restrict s)
{
	return __dlsym(p, s, 0);
}
''',
    'tlsdesc.c': r'''#include <stddef.h>
#include <dynlink.h>

ptrdiff_t __tlsdesc_static()
{
	return 0;
}

weak_alias(__tlsdesc_static, __tlsdesc_dynamic);
''',
    'arm/find_exidx.c': r'''#define _GNU_SOURCE
#include <link.h>
#include <stdint.h>

struct find_exidx_data {
	uintptr_t pc, exidx_start;
	int exidx_len;
};

static int find_exidx(struct dl_phdr_info *info, size_t size, void *ptr)
{
	struct find_exidx_data *data = ptr;
	const ElfW(Phdr) *phdr = info->dlpi_phdr;
	uintptr_t addr, exidx_start = 0;
	int i, match = 0, exidx_len = 0;

	for (i = info->dlpi_phnum; i > 0; i--, phdr++) {
		addr = info->dlpi_addr + phdr->p_vaddr;
		switch (phdr->p_type) {
		case PT_LOAD:
			match |= data->pc >= addr && data->pc < addr + phdr->p_memsz;
			break;
		case PT_ARM_EXIDX:
			exidx_start = addr;
			exidx_len = phdr->p_memsz;
			break;
		}
	}
	data->exidx_start = exidx_start;
	data->exidx_len = exidx_len;
	return match;
}

uintptr_t __gnu_Unwind_Find_exidx(uintptr_t pc, int *pcount)
{
	struct find_exidx_data data;
	data.pc = pc;
	if (dl_iterate_phdr(find_exidx, &data) <= 0)
		return 0;
	*pcount = data.exidx_len / 8;
	return data.exidx_start;
}
''',
}
