"""json2qt -- a pure-rpython DOM renderer for the minibrowser.

This is the rpython port of OpenSourceJesus's Tetra `json2qt.py`. The CPython
original walks a DOM (parsed from a JSON page bundle) and builds a PyQt5 widget
tree in `generate_interface`; here the same dispatch runs as a native Wayland
client through `rpyqt` (software-rendered, no Qt linked, all C generated by
py2c).

Division of labour (see README):
  * `www2json.py`  -- runs under CPython, turns HTML/JS into the JSON bundle and
                      emits `page_data.py` (the "json/py" form of the page).
  * `dom.py`       -- the rpython `Node` tree the renderer walks.
  * `json2qt.py`   -- THIS renderer: `Node.tag()` -> rpyqt widgets.
  * `page_data.py` -- generated: `build_page()` constructs the `Node` tree.

Build (multi-file translation unit):
    python3 -m shivyc.main json2qt.py dom.py page_data.py -o minibrowser
or `make minibrowser`, which also generates the Wayland glue and links wl.

Scope of this first port: the structural/text/list/anchor/heading/rule/input/
button/table dispatch. Not yet ported (tracked in README): live navigation,
forms POST, images, and running page scripts through embedded minipy.
"""
from rpyqt import (QApplication, QWidget, QVBoxLayout, QHBoxLayout, QBoxLayout,
                   QLabel, QPushButton, QHeading, QLink, QLineEdit, QHLine)
from dom import Node
from page_data import build_page

# A single status line at the bottom, updated by the shared activation handler
# so link/button clicks are observably wired through the Wayland event loop.
_status = None


def on_activate() -> None:
    st = _status
    if st is not None:
        st.setText("CLICKED")


def heading_level(tag: "char*") -> int:
    if tag == "h1":
        return 1
    if tag == "h2":
        return 2
    if tag == "h3":
        return 3
    if tag == "h4":
        return 4
    if tag == "h5":
        return 5
    return 6


def is_heading(tag: "char*") -> int:
    if tag == "h1" or tag == "h2" or tag == "h3":
        return 1
    if tag == "h4" or tag == "h5" or tag == "h6":
        return 1
    return 0


def is_structural(tag: "char*") -> int:
    # Containers that contribute no widget of their own -- just recurse.
    if tag == "html" or tag == "head" or tag == "body" or tag == "div":
        return 1
    if tag == "span" or tag == "section" or tag == "article" or tag == "main":
        return 1
    if tag == "header" or tag == "footer" or tag == "nav":
        return 1
    return 0


def is_paragraph(tag: "char*") -> int:
    if tag == "p" or tag == "blockquote" or tag == "cite":
        return 1
    if tag == "dt" or tag == "dd" or tag == "figcaption":
        return 1
    return 0


def render_children(node: "obj", box: "QBoxLayout") -> None:
    n = node.child_count()
    i = 0
    while i < n:
        render_node(node.child(i), box)
        i = i + 1


def render_table(node: "obj", box: "QBoxLayout") -> None:
    # Flatten table/tr/(td|th) into a stack of horizontal rows of labels.
    nrows = node.child_count()
    r = 0
    while r < nrows:
        section = node.child(r)
        stag = section.tag()
        if stag == "tr":
            render_row(section, box)
        elif stag == "tbody" or stag == "thead" or stag == "tfoot":
            render_table(section, box)
        r = r + 1


def render_row(tr: "obj", box: "QBoxLayout") -> None:
    row = QHBoxLayout()
    ncells = tr.child_count()
    c = 0
    while c < ncells:
        cell = tr.child(c)
        ctag = cell.tag()
        if ctag == "td" or ctag == "th":
            row.addWidget(QLabel(cell.get_text()))
        c = c + 1
    box.addLayout(row)


def render_node(node: "obj", box: "QBoxLayout") -> None:
    t = node.tag()

    # 1. structural containers: no widget of their own, recurse in place.
    if is_structural(t):
        render_children(node, box)
        return

    # 2. headings
    if is_heading(t):
        box.addWidget(QHeading(node.get_text(), heading_level(t)))
        return

    # 3. paragraphs and paragraph-like text blocks
    if is_paragraph(t):
        box.addWidget(QLabel(node.get_text()))
        return

    # 4. anchor -> link widget (clicked wired to the activation handler)
    if t == "a":
        link = QLink(node.get_text(), node.get_href())
        link.clicked.connect(on_activate)
        box.addWidget(link)
        return

    # 5. list item -> bulleted label, then any nested block children
    if t == "li":
        box.addWidget(QLabel("- " + node.get_text()))
        render_children(node, box)
        return

    # 6. unordered / ordered list -> recurse (each li renders a bullet)
    if t == "ul" or t == "ol":
        render_children(node, box)
        return

    # 7. rules and breaks
    if t == "hr":
        box.addWidget(QHLine())
        return
    if t == "br":
        box.addWidget(QLabel(""))
        return

    # 8. image -> textual placeholder (real blitting is a later step)
    if t == "img":
        box.addWidget(QLabel("[img]"))
        return

    # 9. form controls
    if t == "input":
        it = node.get_itype()
        if it == "hidden":
            return
        if it == "submit" or it == "button":
            btn = QPushButton(node.get_value())
            btn.clicked.connect(on_activate)
            box.addWidget(btn)
            return
        # text-like inputs -> a line edit showing value/placeholder
        field = QLineEdit(node.get_value())
        field.setPlaceholderText(node.get_placeholder())
        field.returnPressed.connect(on_activate)
        box.addWidget(field)
        return

    if t == "textarea":
        field = QLineEdit(node.get_value())
        box.addWidget(field)
        return

    # 10. button
    if t == "button":
        btn = QPushButton(node.get_text())
        btn.clicked.connect(on_activate)
        box.addWidget(btn)
        return

    # 11. form / figure: sub-container -> new vertical sub-layout
    if t == "form" or t == "figure":
        sub = QVBoxLayout()
        render_children(node, sub)
        box.addLayout(sub)
        return

    # 12. table
    if t == "table":
        render_table(node, box)
        return

    # 13. raw text node
    if t == "#text":
        box.addWidget(QLabel(node.get_text()))
        return

    # 14. fallback: if it has text, show it; then recurse into any children.
    if len(node.get_text()) > 0:
        box.addWidget(QLabel(node.get_text()))
    render_children(node, box)


def main() -> int:
    global _status
    app = QApplication()
    win = QWidget()
    win.setWindowTitle("MINIBROWSER")

    box = QVBoxLayout()
    root = build_page()
    render_node(root, box)

    status = QLabel("READY")
    _status = status
    box.addWidget(status)

    win.setLayout(box)
    return app.exec_(win)
