#!/usr/bin/env python3
"""Package a musl source tree into importable Python modules under shivyc/musl/.

Every musl C source folder (src/aio, src/complex, ...) becomes one module
shivyc/musl/<folder>.py whose FILES dict maps each contained .c path to its raw
text. All headers needed to compile against musl (the public include tree plus
musl's internal build headers) are packaged into shivyc/musl/_headers.py. A
small _manifest.py records the category list and the include-path layout.

At build time shivyc/musl/__init__.py materializes the requested files to a
temporary directory and hands back the include-path arguments, so a user
program can be compiled against musl -- bypassing glibc -- without polluting the
ShivyC source tree with thousands of .h/.c files.

Re-run this whenever the musl fork changes:
    python3 tools/pack_musl.py /home/claude/shivyc-musl shivyc/musl
"""
import os
import sys

# Header directories to package, relative to the musl root. Order matters for
# include resolution (most specific arch dirs first); the loader emits -I flags
# in this order.
PUBLIC_HEADER_DIRS = [
    "arch/x86_64",
    "arch/generic",
    "obj/include",
    "include",
]
INTERNAL_HEADER_DIRS = [
    "obj/src/internal",
    "src/include",
    "src/internal",
]
DEFAULT_DEFINES = ["_XOPEN_SOURCE=700"]


def pyquote(s: str) -> str:
    """Return a Python literal for s, preferring a raw triple-quoted string.

    Raw triple-quoted strings keep the C source readable in the packaged
    modules. They are unusable only if the text contains the chosen delimiter
    or ends in a backslash (a raw string may not end with one); in those rare
    cases we fall back to repr(), which is always correct. Round-trip
    verification below guarantees correctness regardless of which form is used.
    """
    if "'''" not in s and not s.endswith("\\"):
        return "r'''" + s + "'''"
    if '"""' not in s and not s.endswith("\\"):
        return 'r"""' + s + '"""'
    return repr(s)


def read_text(path: str) -> str:
    with open(path, "rb") as f:
        data = f.read()
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        return data.decode("latin-1")


def collect(root: str, subdir: str, ext: str):
    """Yield (relpath_within_subdir, abspath) for files ending in ext."""
    base = os.path.join(root, subdir)
    for dirpath, _dirs, files in os.walk(base):
        for fn in sorted(files):
            if fn.endswith(ext):
                ap = os.path.join(dirpath, fn)
                rel = os.path.relpath(ap, base)
                yield rel.replace(os.sep, "/"), ap


def emit_dict_module(out_path, header_comment, varname, items, extra=""):
    """Write a module defining `varname = { key: <raw text>, ... }`."""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write('"""%s"""\n\n' % header_comment)
        if extra:
            f.write(extra + "\n")
        f.write("%s = {\n" % varname)
        for key, text in items:
            f.write("    %r: %s,\n" % (key, pyquote(text)))
        f.write("}\n")


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: pack_musl.py <musl_root> <out_dir>")
    musl_root = os.path.abspath(sys.argv[1])
    out_dir = os.path.abspath(sys.argv[2])
    os.makedirs(out_dir, exist_ok=True)

    # ---- sources: one module per src/<category> -------------------------
    src_root = os.path.join(musl_root, "src")
    categories = sorted(d for d in os.listdir(src_root)
                        if os.path.isdir(os.path.join(src_root, d)))
    packaged_categories = []
    for cat in categories:
        items = [(rel, read_text(ap))
                 for rel, ap in collect(src_root, cat, ".c")]
        if not items:
            continue
        # Module name must be a valid identifier (e.g. src/aio -> aio).
        mod = cat.replace("-", "_")
        emit_dict_module(
            os.path.join(out_dir, mod + ".py"),
            "Packaged musl source: src/%s/*.c (auto-generated by "
            "tools/pack_musl.py; do not edit by hand)." % cat,
            "FILES", items,
            extra="CATEGORY = %r\n" % cat)
        packaged_categories.append((cat, mod, len(items)))

    # ---- headers: one combined module -----------------------------------
    header_items = []
    for d in PUBLIC_HEADER_DIRS + INTERNAL_HEADER_DIRS:
        for rel, ap in collect(musl_root, d, ".h"):
            header_items.append((d + "/" + rel, read_text(ap)))
    emit_dict_module(
        os.path.join(out_dir, "_headers.py"),
        "Packaged musl headers (auto-generated by tools/pack_musl.py). Keys "
        "are paths relative to the musl root.",
        "HEADERS", header_items)

    # ---- manifest -------------------------------------------------------
    with open(os.path.join(out_dir, "_manifest.py"), "w",
              encoding="utf-8") as f:
        f.write('"""Layout metadata for the packaged musl tree '
                '(auto-generated)."""\n\n')
        f.write("CATEGORIES = [\n")
        for cat, mod, n in packaged_categories:
            f.write("    (%r, %r, %d),\n" % (cat, mod, n))
        f.write("]\n\n")
        f.write("PUBLIC_HEADER_DIRS = %r\n" % (PUBLIC_HEADER_DIRS,))
        f.write("INTERNAL_HEADER_DIRS = %r\n" % (INTERNAL_HEADER_DIRS,))
        f.write("DEFAULT_DEFINES = %r\n" % (DEFAULT_DEFINES,))

    total_src = sum(n for _, _, n in packaged_categories)
    print("packaged %d categories, %d source files, %d headers"
          % (len(packaged_categories), total_src, len(header_items)))
    return musl_root, out_dir, packaged_categories, header_items


if __name__ == "__main__":
    main()
