"""rwayland -- py2c-side integration for first-class Wayland support.

The rpython library lives in `rpy_lib/rwayland.py` (the `Window` API + the
`rw_*` trampolines). This module is the *translator glue generator*: when a
source imports `rwayland`, py2c

  1. bundles `rpy_lib/rwayland.py` into the translation unit (co-compiled),
  2. writes the app-agnostic Wayland runtime `rwayland_rt.{h,c}` to the output
     directory (listeners, shm, registry, dispatch loop -- the boilerplate the
     user would otherwise hand-write in C), and
  3. runs `wayland-scanner` on xdg-shell.xml to emit the client header and
     protocol stubs the runtime needs.

So an end user writes only rpython; every line of C is machine-generated and
identical for every program. Link with `-lwayland-client` (and compile the
generated `rwayland_rt.c` + `xdg-shell-protocol.c` alongside the app).

This mirrors tools/rpy_torch.py: no heavyweight dependency is pulled in -- the
library is one more rpython source, and the runtime is a fixed support file.
"""

import os
import ast
import shutil
import subprocess

LIB_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "rpy_lib")
LIB_FILE = os.path.join(LIB_DIR, "rwayland.py")

_XDG_XML_CANDIDATES = [
    "/usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml",
    "/usr/local/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml",
]


def imports_rwayland(path):
    """True if the rpython source at `path` imports the rwayland module."""
    try:
        tree = ast.parse(open(path, encoding="utf-8").read())
    except Exception:
        return False
    for n in ast.walk(tree):
        if isinstance(n, ast.Import) and any(
                a.name == "rwayland" for a in n.names):
            return True
        if isinstance(n, ast.ImportFrom) and n.module == "rwayland":
            return True
    return False


def needed(files):
    """True if any input file imports rwayland."""
    return any(imports_rwayland(f) for f in files if f.endswith(".py"))


def bundle(files):
    """Append the bundled rpy_lib/rwayland.py iff some input imports it."""
    files = list(files)
    if not os.path.isfile(LIB_FILE):
        return files
    if any(os.path.basename(f) == "rwayland.py" for f in files):
        return files
    if needed(files):
        files.append(LIB_FILE)
    return files


def _find_xdg_xml(files):
    for c in _XDG_XML_CANDIDATES:
        if os.path.isfile(c):
            return c
    for f in files:
        d = os.path.dirname(os.path.abspath(f))
        for cand in (os.path.join(d, "xdg-shell.xml"),
                     os.path.join(d, "protocols", "stable", "xdg-shell",
                                  "xdg-shell.xml")):
            if os.path.isfile(cand):
                return cand
    return None


def emit_runtime(out_dir, files):
    """Write rwayland_rt.{h,c} + scanned xdg-shell files to out_dir.

    Best-effort: returns human-readable notes. Skips (with a note) if
    wayland-scanner or xdg-shell.xml is unavailable, so transpilation still
    succeeds on machines without the Wayland SDK."""
    if not needed(files):
        return []
    return write_runtime(out_dir, files)


def write_runtime(out_dir, files):
    """Write the app-agnostic Wayland runtime + scanned xdg-shell to out_dir,
    unconditionally. Shared by the rwayland and rpyqt integrations (rpyqt binds
    the same runtime without importing the rwayland rpython module)."""
    notes = []
    with open(os.path.join(out_dir, "rwayland_rt.h"), "w") as fh:
        fh.write(RUNTIME_H)
    with open(os.path.join(out_dir, "rwayland_rt.c"), "w") as fh:
        fh.write(RUNTIME_C)
    notes.append("runtime -> %s/rwayland_rt.{h,c}" % out_dir)

    scanner = shutil.which("wayland-scanner")
    xml = _find_xdg_xml(files)
    if scanner and xml:
        hdr = os.path.join(out_dir, "xdg-shell-client-protocol.h")
        code = os.path.join(out_dir, "xdg-shell-protocol.c")
        try:
            subprocess.run([scanner, "client-header", xml, hdr], check=True)
            subprocess.run([scanner, "private-code", xml, code], check=True)
            notes.append(
                "xdg-shell -> %s/xdg-shell-{client-protocol.h,protocol.c}"
                % out_dir)
        except Exception as e:
            notes.append("wayland-scanner failed (%s); run it manually" % e)
    else:
        miss = "wayland-scanner" if not scanner else "xdg-shell.xml"
        notes.append("%s not found; generate xdg-shell-*.{h,c} on the target "
                     "and link -lwayland-client" % miss)
    notes.append("link: cc *.c -lwayland-client")
    return notes


RUNTIME_H = '#ifndef RWAYLAND_RT_H\n#define RWAYLAND_RT_H\n/* rwayland runtime -- generated by tools/py2c.py when a program imports\n * rpy_lib/rwayland.  App-agnostic Wayland (listeners, shm, registry, event\n * loop); calls back into the transpiled rpython program through the fixed\n * rw_* extern contract below.  Link with -lwayland-client. */\n\n#ifdef __cplusplus\nextern "C" {\n#endif\n\n/* ---- contract: the rpython side (rwayland.py) provides these ----------- */\n/* Window geometry + title, read once at startup.                          */\nextern int          rw_width(void);\nextern int          rw_height(void);\nextern const char  *rw_title(void);\n/* Paint the whole framebuffer (XRGB8888, width*height pixels).            */\nextern void         rw_paint(unsigned *fb);\n/* A pointer button event. Returns a packed value: low byte = action,\n * bit 8 = new "button_pressed" state. Actions:\n *   0 RWL_QUIT  1 RWL_MOVE  2 RWL_REDRAW  3 RWL_NONE                       */\nextern int          rw_pointer(int x, int y, int pressed);\n/* A key event. `codepoint` is ASCII (8=backspace, 13=enter, >=32\n * printable); `pressed` is 1 on press, 0 on release. Returns an\n * action like rw_pointer. */\nextern int          rw_key(int codepoint, int pressed);\n\n/* ---- entry point: the rpython side calls this from main() -------------- */\n/* Connect, create the window, run the dispatch loop, clean up.            */\nint rwl_run(void);\n\n#ifdef __cplusplus\n}\n#endif\n#endif /* RWAYLAND_RT_H */\n'

RUNTIME_C = '#define _GNU_SOURCE\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <sys/mman.h>\n#include <unistd.h>\n#include <linux/input-event-codes.h>\n#include <wayland-client.h>\n#include "xdg-shell-client-protocol.h"\n#include "rwayland_rt.h"\n\n#define RWL_QUIT    0\n#define RWL_MOVE    1\n#define RWL_REDRAW  2\n#define RWL_NONE    3\n\nstruct rwl_state {\n    struct wl_display *display;\n    struct wl_registry *registry;\n    struct wl_compositor *compositor;\n    struct wl_shm *shm;\n    struct xdg_wm_base *wm_base;\n    struct wl_seat *seat;\n    struct wl_pointer *pointer;\n    struct wl_keyboard *keyboard;\n\n    struct wl_surface *surface;\n    struct xdg_surface *xdg_surface;\n    struct xdg_toplevel *xdg_toplevel;\n\n    unsigned *pixel_data;\n    struct wl_buffer *buffer;\n    int running;\n\n    int width, height;\n    int pointer_x, pointer_y;\n    int mods_shift;\n    uint32_t last_serial;\n};\n\nstatic void rwl_commit(struct rwl_state *s) {\n    wl_surface_attach(s->surface, s->buffer, 0, 0);\n    wl_surface_damage(s->surface, 0, 0, s->width, s->height);\n    wl_surface_commit(s->surface);\n}\n\nstatic struct wl_buffer *rwl_create_shm_buffer(struct rwl_state *s) {\n    int stride = s->width * 4;\n    int size = stride * s->height;\n    int fd = memfd_create("rwl_shm", MFD_CLOEXEC);\n    if (fd < 0)\n        return NULL;\n    if (ftruncate(fd, size) < 0) { close(fd); return NULL; }\n    s->pixel_data = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);\n    if (s->pixel_data == MAP_FAILED) { close(fd); return NULL; }\n    struct wl_shm_pool *pool = wl_shm_create_pool(s->shm, fd, size);\n    struct wl_buffer *buffer = wl_shm_pool_create_buffer(\n        pool, 0, s->width, s->height, stride, WL_SHM_FORMAT_XRGB8888);\n    wl_shm_pool_destroy(pool);\n    close(fd);\n    return buffer;\n}\n\n/* ---- xdg_surface ------------------------------------------------------- */\nstatic void on_xdg_surface_configure(void *data, struct xdg_surface *xs, uint32_t serial) {\n    xdg_surface_ack_configure(xs, serial);\n    struct rwl_state *s = data;\n    rw_paint(s->pixel_data);\n    rwl_commit(s);\n}\nstatic const struct xdg_surface_listener xdg_surface_listener = {\n    .configure = on_xdg_surface_configure,\n};\n\n/* ---- xdg_toplevel ------------------------------------------------------ */\nstatic void tl_configure(void *d, struct xdg_toplevel *t, int32_t w, int32_t h, struct wl_array *st) {\n    (void)d; (void)t; (void)w; (void)h; (void)st;\n}\nstatic void tl_close(void *d, struct xdg_toplevel *t) {\n    (void)t; ((struct rwl_state *)d)->running = 0;\n}\nstatic void tl_configure_bounds(void *d, struct xdg_toplevel *t, int32_t w, int32_t h) {\n    (void)d; (void)t; (void)w; (void)h;\n}\nstatic void tl_wm_capabilities(void *d, struct xdg_toplevel *t, struct wl_array *c) {\n    (void)d; (void)t; (void)c;\n}\nstatic const struct xdg_toplevel_listener xdg_toplevel_listener = {\n    .configure = tl_configure,\n    .close = tl_close,\n    .configure_bounds = tl_configure_bounds,\n    .wm_capabilities = tl_wm_capabilities,\n};\n\n/* ---- wl_pointer -------------------------------------------------------- */\nstatic void p_motion(void *d, struct wl_pointer *p, uint32_t t, wl_fixed_t sx, wl_fixed_t sy) {\n    (void)p; (void)t;\n    struct rwl_state *s = d;\n    s->pointer_x = wl_fixed_to_int(sx);\n    s->pointer_y = wl_fixed_to_int(sy);\n}\nstatic void p_button(void *d, struct wl_pointer *p, uint32_t serial, uint32_t t,\n                     uint32_t button, uint32_t bstate) {\n    (void)p; (void)t;\n    struct rwl_state *s = d;\n    if (button != BTN_LEFT)\n        return;\n    s->last_serial = serial;\n    int pressed = bstate == WL_POINTER_BUTTON_STATE_PRESSED;\n    int packed = rw_pointer(s->pointer_x, s->pointer_y, pressed);\n    int action = packed & 0xFF;\n    if (action == RWL_QUIT)\n        s->running = 0;\n    else if (action == RWL_MOVE)\n        xdg_toplevel_move(s->xdg_toplevel, s->seat, serial);\n    else if (action == RWL_REDRAW) {\n        rw_paint(s->pixel_data);\n        rwl_commit(s);\n    }\n}\nstatic void p_enter(void *d, struct wl_pointer *p, uint32_t se, struct wl_surface *su, wl_fixed_t x, wl_fixed_t y) {\n    (void)d; (void)p; (void)se; (void)su; (void)x; (void)y;\n}\nstatic void p_leave(void *d, struct wl_pointer *p, uint32_t se, struct wl_surface *su) {\n    (void)d; (void)p; (void)se; (void)su;\n}\nstatic void p_axis(void *d, struct wl_pointer *p, uint32_t t, uint32_t a, wl_fixed_t v) {\n    (void)d; (void)p; (void)t; (void)a; (void)v;\n}\nstatic void p_frame(void *d, struct wl_pointer *p) { (void)d; (void)p; }\nstatic void p_axis_source(void *d, struct wl_pointer *p, uint32_t src) { (void)d; (void)p; (void)src; }\nstatic void p_axis_stop(void *d, struct wl_pointer *p, uint32_t t, uint32_t a) { (void)d; (void)p; (void)t; (void)a; }\nstatic void p_axis_discrete(void *d, struct wl_pointer *p, uint32_t a, int32_t v) { (void)d; (void)p; (void)a; (void)v; }\nstatic const struct wl_pointer_listener pointer_listener = {\n    .enter = p_enter, .leave = p_leave, .motion = p_motion, .button = p_button,\n    .axis = p_axis, .frame = p_frame, .axis_source = p_axis_source,\n    .axis_stop = p_axis_stop, .axis_discrete = p_axis_discrete,\n};\n\n/* ---- wl_keyboard ------------------------------------------------------ */\n/* Dependency-free evdev keycode -> ASCII for a US layout: enough to type into\n * a text field. Shift is tracked from the physical shift keys (no xkbcommon).\n * Unmapped keys return 0 and are ignored. */\nstatic int evdev_to_ascii(uint32_t key, int shift) {\n    switch (key) {\n    case KEY_A: return shift ? \'A\' : \'a\';\n    case KEY_B: return shift ? \'B\' : \'b\';\n    case KEY_C: return shift ? \'C\' : \'c\';\n    case KEY_D: return shift ? \'D\' : \'d\';\n    case KEY_E: return shift ? \'E\' : \'e\';\n    case KEY_F: return shift ? \'F\' : \'f\';\n    case KEY_G: return shift ? \'G\' : \'g\';\n    case KEY_H: return shift ? \'H\' : \'h\';\n    case KEY_I: return shift ? \'I\' : \'i\';\n    case KEY_J: return shift ? \'J\' : \'j\';\n    case KEY_K: return shift ? \'K\' : \'k\';\n    case KEY_L: return shift ? \'L\' : \'l\';\n    case KEY_M: return shift ? \'M\' : \'m\';\n    case KEY_N: return shift ? \'N\' : \'n\';\n    case KEY_O: return shift ? \'O\' : \'o\';\n    case KEY_P: return shift ? \'P\' : \'p\';\n    case KEY_Q: return shift ? \'Q\' : \'q\';\n    case KEY_R: return shift ? \'R\' : \'r\';\n    case KEY_S: return shift ? \'S\' : \'s\';\n    case KEY_T: return shift ? \'T\' : \'t\';\n    case KEY_U: return shift ? \'U\' : \'u\';\n    case KEY_V: return shift ? \'V\' : \'v\';\n    case KEY_W: return shift ? \'W\' : \'w\';\n    case KEY_X: return shift ? \'X\' : \'x\';\n    case KEY_Y: return shift ? \'Y\' : \'y\';\n    case KEY_Z: return shift ? \'Z\' : \'z\';\n    case KEY_1: return shift ? \'!\' : \'1\';\n    case KEY_2: return shift ? \'@\' : \'2\';\n    case KEY_3: return shift ? \'#\' : \'3\';\n    case KEY_4: return shift ? \'$\' : \'4\';\n    case KEY_5: return shift ? \'%\' : \'5\';\n    case KEY_6: return shift ? \'^\' : \'6\';\n    case KEY_7: return shift ? \'&\' : \'7\';\n    case KEY_8: return shift ? \'*\' : \'8\';\n    case KEY_9: return shift ? \'(\' : \'9\';\n    case KEY_0: return shift ? \')\' : \'0\';\n    case KEY_SPACE: return \' \';\n    case KEY_BACKSPACE: return 8;\n    case KEY_ENTER: return 13;\n    case KEY_MINUS: return shift ? \'_\' : \'-\';\n    case KEY_EQUAL: return shift ? \'+\' : \'=\';\n    case KEY_DOT: return shift ? \'>\' : \'.\';\n    case KEY_COMMA: return shift ? \'<\' : \',\';\n    case KEY_SLASH: return shift ? \'?\' : \'/\';\n    default: return 0;\n    }\n}\n\nstatic void kb_keymap(void *d, struct wl_keyboard *k, uint32_t fmt, int32_t fd, uint32_t size) {\n    (void)d; (void)k; (void)fmt; (void)size;\n    if (fd >= 0) close(fd);\n}\nstatic void kb_enter(void *d, struct wl_keyboard *k, uint32_t serial, struct wl_surface *su, struct wl_array *keys) {\n    (void)d; (void)k; (void)serial; (void)su; (void)keys;\n}\nstatic void kb_leave(void *d, struct wl_keyboard *k, uint32_t serial, struct wl_surface *su) {\n    (void)d; (void)k; (void)serial; (void)su;\n}\nstatic void kb_key(void *d, struct wl_keyboard *k, uint32_t serial, uint32_t t, uint32_t key, uint32_t kstate) {\n    (void)k; (void)serial; (void)t;\n    struct rwl_state *s = d;\n    int pressed = kstate == WL_KEYBOARD_KEY_STATE_PRESSED;\n    if (key == KEY_LEFTSHIFT || key == KEY_RIGHTSHIFT) { s->mods_shift = pressed; return; }\n    if (!pressed) return;\n    int cp = evdev_to_ascii(key, s->mods_shift);\n    if (!cp) return;\n    int packed = rw_key(cp, 1);\n    int action = packed & 0xFF;\n    if (action == RWL_QUIT) s->running = 0;\n    else if (action == RWL_REDRAW) { rw_paint(s->pixel_data); rwl_commit(s); }\n}\nstatic void kb_modifiers(void *d, struct wl_keyboard *k, uint32_t serial, uint32_t dep, uint32_t lat, uint32_t lock, uint32_t group) {\n    (void)d; (void)k; (void)serial; (void)dep; (void)lat; (void)lock; (void)group;\n}\nstatic void kb_repeat_info(void *d, struct wl_keyboard *k, int32_t rate, int32_t delay) {\n    (void)d; (void)k; (void)rate; (void)delay;\n}\nstatic const struct wl_keyboard_listener keyboard_listener = {\n    .keymap = kb_keymap, .enter = kb_enter, .leave = kb_leave, .key = kb_key,\n    .modifiers = kb_modifiers, .repeat_info = kb_repeat_info,\n};\n\n/* ---- wl_seat ----------------------------------------------------------- */\nstatic void seat_caps(void *d, struct wl_seat *seat, uint32_t caps) {\n    struct rwl_state *s = d;\n    if ((caps & WL_SEAT_CAPABILITY_POINTER) && !s->pointer) {\n        s->pointer = wl_seat_get_pointer(seat);\n        wl_pointer_add_listener(s->pointer, &pointer_listener, s);\n    }\n    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && !s->keyboard) {\n        s->keyboard = wl_seat_get_keyboard(seat);\n        wl_keyboard_add_listener(s->keyboard, &keyboard_listener, s);\n    }\n}\nstatic void seat_name(void *d, struct wl_seat *seat, const char *name) {\n    (void)d; (void)seat; (void)name;\n}\nstatic const struct wl_seat_listener seat_listener = {\n    .capabilities = seat_caps, .name = seat_name,\n};\n\n/* ---- xdg_wm_base ping/pong -------------------------------------------- */\nstatic void wm_base_ping(void *d, struct xdg_wm_base *b, uint32_t serial) {\n    (void)d; xdg_wm_base_pong(b, serial);\n}\nstatic const struct xdg_wm_base_listener wm_base_listener = { .ping = wm_base_ping };\n\n/* ---- registry ---------------------------------------------------------- */\nstatic void reg_global(void *d, struct wl_registry *r, uint32_t id,\n                       const char *iface, uint32_t version) {\n    (void)version;\n    struct rwl_state *s = d;\n    if (strcmp(iface, "wl_compositor") == 0)\n        s->compositor = wl_registry_bind(r, id, &wl_compositor_interface, 4);\n    else if (strcmp(iface, "wl_shm") == 0)\n        s->shm = wl_registry_bind(r, id, &wl_shm_interface, 1);\n    else if (strcmp(iface, "xdg_wm_base") == 0) {\n        s->wm_base = wl_registry_bind(r, id, &xdg_wm_base_interface, 1);\n        xdg_wm_base_add_listener(s->wm_base, &wm_base_listener, s);\n    } else if (strcmp(iface, "wl_seat") == 0) {\n        s->seat = wl_registry_bind(r, id, &wl_seat_interface, 7);\n        wl_seat_add_listener(s->seat, &seat_listener, s);\n    }\n}\nstatic void reg_global_remove(void *d, struct wl_registry *r, uint32_t id) {\n    (void)d; (void)r; (void)id;\n}\nstatic const struct wl_registry_listener registry_listener = {\n    .global = reg_global, .global_remove = reg_global_remove,\n};\n\n/* ---- entry point ------------------------------------------------------- */\nint rwl_run(void) {\n    struct rwl_state s;\n    memset(&s, 0, sizeof s);\n    s.running = 1;\n    s.width = rw_width();\n    s.height = rw_height();\n\n    s.display = wl_display_connect(NULL);\n    if (!s.display) {\n        fprintf(stderr, "rwayland: failed to connect to Wayland display\\n");\n        return 1;\n    }\n    s.registry = wl_display_get_registry(s.display);\n    wl_registry_add_listener(s.registry, &registry_listener, &s);\n    wl_display_roundtrip(s.display);\n\n    if (!s.compositor || !s.shm || !s.wm_base) {\n        fprintf(stderr, "rwayland: missing core Wayland interfaces\\n");\n        return 1;\n    }\n    s.buffer = rwl_create_shm_buffer(&s);\n    if (!s.buffer) {\n        fprintf(stderr, "rwayland: failed to create shm buffer\\n");\n        return 1;\n    }\n\n    s.surface = wl_compositor_create_surface(s.compositor);\n    s.xdg_surface = xdg_wm_base_get_xdg_surface(s.wm_base, s.surface);\n    xdg_surface_add_listener(s.xdg_surface, &xdg_surface_listener, &s);\n    s.xdg_toplevel = xdg_surface_get_toplevel(s.xdg_surface);\n    xdg_toplevel_add_listener(s.xdg_toplevel, &xdg_toplevel_listener, &s);\n    xdg_toplevel_set_title(s.xdg_toplevel, rw_title());\n\n    wl_surface_commit(s.surface);\n    wl_display_roundtrip(s.display);\n\n    while (s.running && wl_display_dispatch(s.display) != -1)\n        ;\n\n    if (s.keyboard) wl_keyboard_destroy(s.keyboard);\n    wl_buffer_destroy(s.buffer);\n    xdg_toplevel_destroy(s.xdg_toplevel);\n    xdg_surface_destroy(s.xdg_surface);\n    wl_surface_destroy(s.surface);\n    wl_display_disconnect(s.display);\n    return 0;\n}\n'
